<?php echo $this->inlineScript() ?>
   
  <script type="text/javascript">
  
    $(document).ready(function() {
        
       $('.fancy').fancybox({
            afterClose: function () {
                parent.location.reload(true);
            }
       });
       
       
    });
    
    
    window.setTimeout(function() {
        $(".alert-message").fadeTo(500, 0).slideUp(500, function(){
            $(this).remove(); 
        });
    }, 4000);

</script>
 
