<div style="text-align: right">
    <div style="float:right; padding-left:16px;"><img src="/images/765-default-avatar.png" width="80px" height="80px"></div>
    <h3>Hola, <?php echo $this->zfcUserDisplayName() ?>!</h3>
  	    <a href="<?php echo $this->url('zfcuser/perfil') ?>">Perfil |</a>
		    <a href="<?php echo $this->url('zfcuser/logout') ?>">Cerrar sesión</a>
   
    <div style="clear:both;"></div>
</div>