<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Listado de Grupos de Trabajo</h3>
	</div>
<?php if ($this->isAllowed('roles', 'crear')) { ?> 
	<div class="toolbardt">
		<a class="btn btn-success" href="/grupo-trabajo/crear">
		<span class="glyphicon glyphicon-list-alt"></span> Nuevo</a>
	</div>
<?php } ?>


<table class="table table-hover">
	<tr>
	    <th>ID</th>
	    <th>Nombre</th>
		<th>Descripción</th>
		<th>&nbsp;</th>
		
	</tr> 
<?php $this->partialloop()->setObjectKey('grupotrabajo');
echo $this->partialloop('rowGrupoTrabajo', $this->grupotrabajo) ?>
</table>
<?php  echo ( count($this->grupotrabajo) > 5 ) ? $this->paginationControl($this->grupotrabajo, 'Sliding', 'pager.phtml', array('lang'=>$this->lang, 'controller'=>'grupo-trabajo')) : ""; ?>

</div>
