<div class="contenedor">
        <div class="iz">
            <h2><b>verano</b>de<b>emociones</b></h2><div class="institucional">
                    <p>Presidencia de  la Nación, a través del Ministerio de Cultura y junto a los demás  ministerios que conforman el  Gobierno Nacional, este verano van a decir  presente en todo el país acercando actividades culturales, científicas y  recreativas a cinco puntos elegidos por millones de argentinos para  veranear.</p>
<p>&ldquo;Verano  de Emociones&rdquo;  es la campaña de verano 2015 organizada por el Gobierno  Nacional  que lleva actividades para toda la familia a los lugares de  veraneo. Todo con entrada libre y gratuita, desde los primeros días de  enero hasta fin de febrero.
</p>
<p>Los cinco lugares seleccionados para este Verano de Emociones son: <strong>San Marcos Sierras</strong>, Córdoba; <strong>Las Grutas</strong>, Río Negro; <strong>San Rafael</strong>, Mendoza; <strong>Ezeiza</strong> y <strong>Mar del Plata</strong>, Provincia de Buenos Aires.
</p>
<p>Este  verano, además de todo lo que hacés en tu lugar preferido de vacaciones  vas a poder ver dinosaurios, participar de  recitales, obras de teatro,  muestras, conferencias, vas a poder jugar ajedrez, aprender a programar, probar comidas típicas, ver cine, aprender distintos deportes.</p>
<p>También vas a poder disfrutar de las tradicionales <strong>Fiestas Nacionales</strong>, de las más de <strong>90 Casas del Bicentenario</strong> y de los <strong>Carnavales Federales de la Alegría</strong>.</p>
<p>Para  seguir profundizando el camino de integración y acceso a las distintas  expresiones culturales en todo nuestro territorio, nada mejor que tomar  esta ruta cultural y disfrutar con alegría.</p>
<p>Este verano vas a emocionarte como nunca.  <strong>Vení a disfrutar de tu país. Viví a un verano de emociones. </strong></p>
                </div>
                <ul class="mLinks">
                        <li> <div data-ancla="1" class="link">Inicio</div> </li>
                        <li> <div data-ancla="2" class="link">Disfrutá, divertite, conocé</div> </li>
                        <li> <div data-ancla="3" class="link">Elegí tu lugar</div> </li>
                        <li> <div data-ancla="8" class="link">Galería</div> </li>

                </ul><!--mLinks-->
                
        </div><!--iz-->
        <div class="clear"></div>
        <div class="pie">
                <div class="contePie">
                        
                                                <div class="img"><img width="100%" src="/img/logoisologo.png"></div>
                        <div class="clear"></div>
                </div><!--contePie-->
        </div><!--pie--> 
</div><!--contenedor-->