<div class="contenedor">
        <div class="iz" style="width: 94%;">
            <h2><b>verano</b>de<b>emociones</b></h2>
            
            <div class="institucional">
<p><strong>Presidencia de la Nación</strong>, a través del Ministerio de Cultura y junto a los demás ministerios que conforman el  Gobierno Nacional, este verano dicen presente en todo el país acercando actividades culturales, científicas y recreativas a cinco puntos elegidos por millones de argentinos para veranear.</p>
<p>&ldquo;Verano de Emociones&rdquo;  es la campaña organizada por el Gobierno Nacional  que lleva actividades para toda la familia a los lugares de veraneo. Todo con entrada libre y gratuita. </p>
<p>Los cinco lugares seleccionados son: San Marcos Sierras, Córdoba; Las Grutas, Río Negro; San Rafael, Mendoza; Ezeiza y Mar del Plata, Provincia de Buenos Aires.</p>
<p>Este verano, además de todo lo que haces en tu lugar preferido de vacaciones vas a poder ver dinosaurios, participar de  recitales, obras de teatro, muestras, conferencias, jugar ajedrez, aprender a programar, probar comidas típicas, ver cine y practicar distintos deportes.</p>
<p>También vas a disfrutar de las tradicionales Fiestas Nacionales, de las más de 90 Casas del Bicentenario y de los Carnavales Federales de la Alegría.</p>
<p>Para seguir profundizando el camino de integración y acceso a las distintas expresiones culturales en todo nuestro territorio, nada mejor que tomar esta ruta cultural y disfrutar con alegría.</p>
<p><strong>Este verano vas a emocionarte como nunca. Vení a disfrutar de tu país.<br />
  Viví a un verano de emociones.</strong></p>        
            </div>
                <ul class="mLinks">
                        <li> <div data-ancla="1" class="link">Inicio -<br>VERANO DE EMOCIONES</div> </li>
                        <li> <div data-ancla="2" class="link">Disfrutá, divertite, conocé</div> </li>
                                        <li> <div data-ancla="3" class="link">Elegí tu lugar</div><ul>
                                                <li><div data-idajax="1" class="btnDespleDer">Mar del Plata</div></li>
                                                <li><div data-idajax="2" class="btnDespleDer">Ezeiza</div></li>
                                                <li><div data-idajax="3" class="btnDespleDer">San Rafael</div></li>
                                                <li><div data-idajax="4" class="btnDespleDer">San Marcos Sierras</div></li>
                                                <li><div data-idajax="5" class="btnDespleDer">Las Grutas</div></li>
                                            </ul> </li>
                        
                        <li> <div data-ancla="8" class="link">Galería</div> </li>

                </ul><!--mLinks-->
                
        </div><!--iz-->
        <div class="clear"></div>
        <div class="pie">
                <div class="contePie"><div class="social">
						<a target="_blank" href="https://www.facebook.com/pages/Verano-de-Emociones/1605302536365064">Facebook</a>
						<a target="_blank" href="https://twitter.com/VeranoEmociones">Twitter</a>
						<a target="_blank" href="https://www.flickr.com/photos/129741112@N06/">Flickr</a>
						<a target="_blank" href="https://www.youtube.com/TVPublicaArgentina">YouTube</a>
					</div>
                        
                                                <div class="img"><img width="100%" src="/img/logoisologo.png"></div>
                        <div class="clear"></div>
                </div><!--contePie-->
        </div><!--pie--> 
</div><!--contenedor-->