<div class="item">
    <div class="noticap"><h1><?php echo $this->escapeHtml($this->noticia->getTitle()); ?></h1><p>
            <?php echo $this->noticia->getCopete(); ?>
        </p></div>                                                                                                           
    <img src="<?php echo $this->noticia->getImagen_url(); ?>" width="190" height="190" alt="Urraka en San Rafael 3">
</div>


