<tr>
    <td><?php echo $this->escapeHtml($this->usuario->getId());?></td>
    <td><?php echo $this->escapeHtml($this->usuario->getUsername());?></td>
    <td><?php echo $this->escapeHtml($this->usuario->getEmail());?></td>
    <td><?php echo $this->escapeHtml($this->usuario->getOrganismo()->getNombre());?></td>
    
    <td>
    <?php if ($this->isAllowed('usuarios', 'editar')) { ?>
        <a title="Editar" class="btn btn-warning" href="<?php echo $this->url('usuarios',array('action'=>'editar', 'id' => $this->usuario->getId()));?>">
        <span class="glyphicon glyphicon-pencil"></span></a>
    <?php } ?>
    <?php if ($this->isAllowed('usuarios', 'apapelera')) { ?>
        <a class="btn btn-danger" title="Borrar" href="#" 
            onclick="return MyDialogs.loadConfirmationModal('<?php echo $this->usuario->getId() ?>',
            '<?php echo $this->url('usuarios', array('action' => 'apapelera', 'id' => $this->usuario->getId()))?>', 
                'El siguiente usuario será eliminada', 
                '<?php echo $this->usuario->getEmail() ?>','');"><span class="glyphicon glyphicon-trash"></span></a>
    <?php } ?>
	<?php /* if ($this->isAllowed('usuarios', 'informe')) { ?>
        <a title="Ver Informe" class="btn btn-info fancybox dropdown-toggle" data-fancybox-type="iframe" href="<?php echo $this->url('usuarios',array('action'=>'informe', 'id' => $this->usuario->getId()));?>">
        <span class="glyphicon glyphicon-list-alt"></span></a>
    <?php } */ ?>
      
    </td>
</tr>
