<div style="clearfix" class="pager">
<?php if ($this->pageCount): ?>
    <div class="pagination pagination-centered">
        <ul>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->controller, array('action' => $this->action,'page' => $this->first, /*'order_by' => $order_by, 'order' => $order,*/)); ?>">&laquo;</a></li>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->controller, array('action' => $this->action,'page' => $this->previous, /*'order_by' => $order_by, 'order' => $order,*/)); ?>">&lsaquo;</a></li>


            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>><a href="<?php echo $this->url($this->controller, array('action' => $this->action, 'id' => $this->solicitud_id, 'page' => $page, 'order_by' => $this->order_by, 'order' => $this->order,)); ?>">
                        <?php echo $page; ?>
                    </a></li>
            <?php endforeach; ?>

            <!-- Next page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->controller, array('action' => $this->action,'page' => $this->next,/* 'order_by' => $order_by, 'order' => $order,*/)); ?>">&rsaquo;</a></li>
            <!-- Last page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->controller, array('action' => $this->action,'page' => $this->last,/* 'order_by' => $order_by, 'order' => $order,*/)); ?>">&raquo;</a></li>
        </ul>
    </div>
<?php endif; ?>
</div>
<?php /*
$url = $this->url($this->controller, array('action'=>$this->action,'lang'=>$this->lang,'page'));
$parameterGet = $this->Requesthelper();
if ($parameterGet != "") $parameterGet = "?".$parameterGet; ?>

<?php if ($this->pageCount): ?>
<div style="text-align: center;">
      <!-- Previous page link -->
  <ul class="pagination">
      <?php if (isset($this->previous)): ?>
      <li><a class="" href="<?php echo $url.'/pag/1'; ?>">Primero</a></li>
  <li><a class="" href="<?php echo $url.'/pag/'.$this->previous.$parameterGet; ?>">Anterior</a></li>     
      <?php else: ?>
      <li class="disabled" ><a>Primero</a></li>
      <li class="disabled"><a>Anterior</a></li>
      <?php endif; ?>
      
      <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
    <li><a href="<?php echo $url.'/pag/'.$page.$parameterGet; ?>"><?php echo $page; ?></a></li>
            <?php else: ?>
    <li class="active"><a href="<?php echo $url.'/pag/'.$page.$parameterGet; ?>"><?php echo $page; ?></a></li>
            <?php endif; ?>
      <?php endforeach; ?>
      
      <?php if (isset($this->next)): ?>
        <li><a class="disabled" href="<?php echo $url.'/pag/'.$this->next.$parameterGet; ?>">Siguiente</a></li>
        <li><a class="disabled" href="<?php echo $url.'/pag/'.$this->pageCount.$parameterGet; ?>">Ultimo</a></li>
        <?php else: ?>         
        <li><a>Siguiente</a></li>
        <li><a>Ultimo</a></li>
      <?php endif; ?>
    </ul>
</div>
<?php endif; */ ?>
