<html lang="es">
  <head>
  <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>
  <meta charset="UTF-8">
      <?php $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
       				->appendStylesheet($this->basePath() . '/css/smoothness/jquery-ui-1.10.3.custom.css')
    				->appendStylesheet(array('rel' => 'stylesheet/less', 'href' => $this->basePath() . '/bootstrap-3.0.0/less/bootstrap.less'))
    				->appendStylesheet(array('rel' => 'stylesheet/less', 'href' => $this->basePath() . '/css/style.less'));
    
    echo $this->headLink ();

    $this->headScript()->appendFile($this->basePath() . '/js/html5.js', 'text/javascript',array('conditional' => 'lt IE 9'))
    						  ->appendFile($this->basePath() . '/js/jquery-1.10.2.min.js', 'text/javascript')
    						  ->appendFile($this->basePath() . '/js/jquery-ui-1.10.3.custom.js', 'text/javascript')
    						  ->appendFile($this->basePath() . '/js/less-1.4.1.min.js', 'text/javascript');
   						

    echo $this->headScript();
    ?>
    
  </head>
  <body>
      <?php echo $this->content; ?>
  </body>
</html>
