<?php if ($this->data['idactividad'] == 'fiestas') { ?>
    <div id="bgLug" class="bgLug btnFullImg" style="background: url('/img/bg_red.jpg') fixed" >
        <div id="closeLug" class="closeLug"></div>
        <div id="nombreLug" class="nombreLug fullImgOcultar">Fiestas Nacionales</div>
        <div id="descripcionLug" class="descripcionLug fullImgOcultar">
            <p>Las Fiestas Nacionales son un reflejo de la esencia y la identidad de los pueblos de nuestro país, en las que participan las comunidades y fortalecen así la diversidad cultural de Argentina al reforzar las características propias de cada lugar.</p>

            <p>Te presentamos el cronograma de las Fiestas Nacionales que este verano vas a poder disfrutar en todo el país: artesanías, automovilismo, corvinas, folclore, carnaval, chamamé, cebada, quesos, playas de río, pesca y mucho más. </p>
            <p>Para seguir profundizando el camino de integración y acceso a las distintas expresiones culturales en todo nuestro territorio, nada mejor que tomar esta ruta cultural y disfrutar con alegría.</p>
            <p>Este verano también podés emocionarte con las Fiestas Nacionales. Vení a disfrutar de tu país. Vení a un verano lleno de emociones</p>
            <br>
            
            <table  cellspacing="6" cellpadding="6" width="100%">
  <tr>
    <td colspan="2" valign="top"><h4>ENERO</h4></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Festival Nacional de la Chacarera</strong><br />
      Ciudad de Santiago del Estero<br />
      Enero 2 al 4</p></td>
    <td width="60%" valign="top"><p>Festival de la música folklórica santiagueña con la participación de   artistas de renombre. Feria   artesanal. Elección de la mejor chacarera inédita. <br />
    Sede:   Plaza Añoranzas. </p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional del Chivo – Fiesta Provincial del   Cordero </strong><br />
      Malargüe, Mendoza<br />
      Enero 5 al 10</p></td>
    <td width="60%" valign="top"><p>Exposición caprina y ovina. Espectáculos artísticos, festival y concurso   de canto y danza.</p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional de la Cebada Cervecera</strong><br />
      Puan, Buenos Aires<br />
      Enero 8 al 11</p></td>
    <td width="60%" valign="top"><p>Exposición y concurso de muestras de cebada cervecera, charlas técnicas. Actividades culturales y   deportivas.  Espectáculos artísticos,   asado a la criolla.</p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional del Lago</strong><br />
      Federación, Entre Ríos<br />
      Enero 8 al 11</p></td>
    <td width="60%" valign="top"><p>Importante festival con espectáculos de música y danzas, a orillas del   embalse Salto Grande. Tradicional procesión náutica y fuegos artificiales.   Torneo de pesca de costa y embarcados, campeonatos deportivos, concursos   culturales, actividades recreativas y para niños. Paseo de artesanías y patio   de comidas. <br />
    Sede: Anfiteatro Juancho Garcilazo.</p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><br clear="all" />
      <br clear="all" />
      <p><strong>Fiesta Nacional de Doma y Folklore</strong><br />
        Jesús María, Córdoba<br />
        Enero 8 al 19<strong></strong></p></td>
    <td width="60%" valign="top"><p>Festival nocturno de doma y folklore, jineteadas, entrevero de tropillas,   rodeo campero. Espectáculos de música folklórica y humor con la participación   de artistas de renombre. Muestra turística y artesanal.<br />
    Sede: Paseo Federal.</p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional de la Playa de Río</strong><br />
      Concepción del Uruguay, Entre Ríos<br />
      Enero 9 al 11</p></td>
    <td width="60%" valign="top"><p>Actividades culturales, recreativas y deportivas, espectáculos   musicales.<br />
    Sede:   Banco Pelay </p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional del Chamamé</strong><br />
      Ciudad de Corrientes<br />
      Enero 16 al 25<strong></strong></p></td>
    <td width="60%" valign="top"><p>Festival de la música autóctona, con la presentación de números musicales   por noche, cuadros argumentales y danzas folklóricas, con la participación de   los ganadores del pre-festival.<br />
    Sede: Anfiteatro Mario del Tránsito Cocomarola.</p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional Capital Nacional del Carnaval</strong><br />
      Ciudad de Corrientes<br />
      Enero 23, 24, 30 y 31; febrero 6, 7, 13, 14, 16 y 17<strong></strong></p></td>
    <td width="60%" valign="top"><p>Desfile de las comparsas Ara Berá, Arandú Beleza y Sapucay - con más de   600 integrantes - . Agrupaciones musicales Imperio Bahiano, Kamandukahia   Sambanda, Samba Show y Samba Total. Show de comparsas, de agrupaciones y   escuelas de samba.<br />
    Sede: Corsódromo de la ciudad.</p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Festival de la Salamanca</strong><br />
      La Banda, Santiago del Estero<br />
      Enero 28 al 2 de febrero<strong></strong></p></td>
    <td width="60%" valign="top"><p>Festival folklórico con la actuación de las principales figuras del   folklore nacional y del ámbito provincial.<br />
    Sede: Club Sarmiento.</p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional del Automovilismo</strong><br />
      Balcarce, Buenos Aires<br />
      Enero 29 al 1° de febrero</p></td>
    <td width="60%" valign="top"><p>Museo Fangio en la calle. Muestra de maquetas de automóviles. Exhibición   de karting en circuito callejero con pilotos de Turismo Carretera.   Competencias. Desfile de autos de colección. Club de autos especiales,   tunning. Feria de artesanos. Espectáculos artísticos.<br />
    Sede: Anfiteatro del Parque Municipal Cerro El Triunfo.</p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Provincial de la Miel</strong><br />
      San Marcos Sierras, Córdoba<br />
      Enero 30 al 1° de febrero</p></td>
    <td width="60%" valign="top"><p>Espectáculo artístico, festival folklórico y otras   manifestaciones culturales. Feria de productos regionales, muestras plásticas   y artesanales; desfile de carrozas.</p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional del Lúpulo</strong> <br />
      El Bolsón, Río Negro<br />
      Enero 30 al 1° de febrero</p></td>
    <td width="60%" valign="top"><p>Fiesta tradicional que  conmemora   la antigua celebración popular por la llegada de la cosecha de las flores del   lúpulo. Feria de productos regionales. Actividades culturales, muestras   artísticas, competencias deportivas. Números artísticos en el escenario mayor.   Puestos de cerveza artesanal, asado y comidas típicas. <br />
    Sede: Predio del Aeropuerto.</p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><br clear="all" />
      <p><strong>Fiesta Nacional de la Doma y el Foklore</strong><br />
        Intendente Alvear, La Pampa<br />
        Enero 31 al 7 de febrero</p></td>
    <td width="60%" valign="top"><p>Campeonato de Jinetes Aficionados Pampeanos. Jineteada de petisos, clasificatoria   para la noche central. Festival folklórico.<br />
    Sede: Club Social y Atlético Ferro Carril Oeste.</p></td>
  </tr>
</table><br>
<table border="1" cellspacing="6" cellpadding="6" width="100%">
  <tr>
    <td colspan="2" valign="top"><h4>FEBRERO</h4></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional de los Jardines</strong><br />
      Villa La Angostura, Neuquén<br />
      Febrero 5 al 8</p></td>
    <td width="60%" valign="top"><p>Desfile de   carrozas, murgas, comparsas, paella gigante, destreza criolla, muestras   plásticas, artesanales y fotográficas y shows musicales.</p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional de la Manzana</strong><br />
      General Roca, Río Negro<br />
      Febrero 5 al 8<strong></strong></p></td>
    <td width="60%" valign="top"><p>Fiesta popular y exposición productiva. Bendición de los frutos,  manifestaciones culturales, espectáculos   artísticos, competencias deportivas, desfile de carrozas.</p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Festival Nacional de Peñas</strong><br />
      Villa María, Córdoba<br />
      Febrero, 5 al 9<strong></strong></p></td>
    <td width="60%" valign="top"><p>Importante festival de música popular, con la actuación de destacadas   figuras, inicialmente dedicado a la música folklórica y que con el tiempo fue   incluyendo variedad de géneros populares. <br />
    <strong>Sede:   Anfiteatro Municipal Centenario.</strong><strong> </strong></p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional de la Corvina</strong><br />
      Herradura, Formosa<br />
      Febrero 6 al 8</p></td>
    <td width="60%" valign="top"><p>Encuentro de pescadores en la laguna Herradura, en busca de la corvina   del río. Procesión náutica con la imagen de la Virgen del Carmen. Desfile   tradicionalista, exhibición de motonáutica. Actividades náuticas, deportivas,   recreativas y culturales. Peña oficial &ldquo;La Corvina&rdquo;, espectáculos musicales.   Concursos de pesca variada de costa con devolución, de pesca embarcada a remo   y a motor. Exposición comercial, artesanal y de servicios   turísticos.</p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional del Valle del Sol</strong><br />
      Villa de Merlo, San Luis<br />
      Febrero 6 al 9</p></td>
    <td width="60%" valign="top"><p>Espectáculos artísticos, actividades culturales,   comidas típicas.<br />
    Sede: Balneario Municipal.</p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional de las Artesanías</strong><br />
      Colón, Entre Ríos<br />
      Febrero 7 al 16<strong></strong></p></td>
    <td width="60%" valign="top"><p>Feria artesanal donde exponen más de 500 artesanos   del país y de países limítrofes, donde se llevan   a cabo talleres, seminarios y espectáculos musicales.<br />
    Sede: Parque &ldquo;Dr. Herminio J. Quirós&rdquo;.</p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional de la Chaya</strong><br />
      Ciudad de La Rioja<br />
      Febrero 13 al 17</p></td>
    <td width="60%" valign="top"><p>Celebración del carnaval. Festivales, música y danzas, fiestas de harina   y albahaca, corsos carnavalescos y gastronomía regional. Espectáculo   folklórico en el Estadio del Centro. </p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional del Golfo Azul</strong><br />
      Las Grutas, Río Negro<br />
      Febrero 14 al 17</p></td>
    <td width="60%" valign="top"><p>Certámenes náuticos y diversas expresiones   culturales. Se realiza la &quot;salmonada&quot;, que consiste en armar   fogones a lo largo de la calle, donde se sirve salmón y otros frutos de mar.   Espectáculos musicales en <br />
    Sede: Boulevard entre la tercera y cuarta bajada. </p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional del Mate</strong><br />
      Paraná, Entre Ríos<br />
      Febrero</p></td>
    <td width="60%" valign="top"><p>Exposición y degustación de yerbas. Espectáculos musicales, noches de folklore, tango,   rock, música tropical y latina. <br />
    Sede: Plaza de las Colectividades.</p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional del Queso</strong><br />
      Tafí del Valle, Tucumán<br />
      Febrero 20 al 23</p></td>
    <td width="60%" valign="top"><p>Degustación de quesos tafinistos y comidas típicas. Muestra artesanal y   festival folklórico.</p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional del Sol</strong><br />
      Ciudad de San Juan<br />
      Febrero 24 al 28<strong></strong></p></td>
    <td width="60%" valign="top"><p>Feria gastronómica y exposición agrícola e industrial, en el predio   ferial del Parque de Mayo, con la actuación de grupos musicales por las   noches. Espectáculo de coreografía, luz, color y sonido<br />
    Sede: Autódromo y Quebrada de Zonda. </p></td>
  </tr>
  <tr>
    <td width="40%" valign="top"><p><strong>Fiesta Nacional del Pacú</strong><br />
      Esquina, Corrientes<br />
      Febrero 27 al 4 de marzo</p></td>
    <td width="60%" valign="top"><p>Torneo de pesca deportiva del   pacú y festival folklórico. </p></td>
  </tr>
</table>
            
        </div>
    </div><!--
    
    
    
    CASAS
    
    
    
    
    
    -->
<?php } else if ($this->data['idactividad'] == 'casas') { ?>
    <div id="bgLug" class="bgLug btnFullImg" style="background: url('/img/bg_green.jpg') fixed" >

        <div id="closeLug" class="closeLug"></div>
        <div id="nombreLug" class="nombreLug ">Casas de la Historia y la Cultura del Bicentenario</div>
        <div id="descripcionLug" class="descripcionLug">
            <p>Las Casas de la Historia y la Cultura del Bicentenario abren sus puertas este verano, en más de 90 lugares del pais, con obras teatrales, espectáculos, música en vivo, propuestas audiovisuales, charlas debates con referentes de la cultura y talleres para toda la familia para que visite todo el público. 
            </p>
            <p>Las Casas son lugares destinados al desarrollo de actividades culturales, educativas y recreativas creadas para que artistas y colectivos puedan fomentar sus proyectos culturales de las comunidades en donde están insertas.
            </p>
            <p>Las actividades comienzan el 7 de enero y continúan hasta el 16 de febrero,  y son todas gratuitas.
            </p>
            <br>
            <br>
            <h3>CAFE CULTURA</h3>
            <br>
  <p>9-10/01/2015 en Santa Rosa, LA PAMPA<br>Las Amaro</p>
<p>08/9/01/2015 en Santa Fe Capital, SANTA FE<br>Los Hermanos Queridos – Obra Teatral (Norberto Gonzalo)</p>
<p>18-19/01/2015 en Necochea, BUENOS AIRES<br>Los Hermanos Queridos – Obra Teatral (Norberto Gonzalo)</p>
<p>24/01/2015 en Capital Federal, CABA<br>Los Hermanos Queridos – Obra Teatral (Norberto Gonzalo)</p>
<p>10/01/2015 en El Trébol, SANTA FE<br>Los Hermanos Queridos – Obra Teatral (Norberto Gonzalo)</p>
<p>11/01/2015 en Venado Tuerto, SANTA FE<br>Los Hermanos Queridos – Obra Teatral (Norberto Gonzalo)</p>
<p>16/01/2015 en Curuzu Cuatiá, CORRIENTES<br>Urraka</p>
<p>16/01/2015 en San Vicente, MISIONES<br>Carlos Balmaceda</p>
<p>16/01/2015 en San Salvador de Jujuy, JUJUY<br>Juan Falú</p>
<p>16-17/01/2015 en Santo Pipo, MISIONES<br>Mariana Baraj</p>
<p>17/01/2015 en Goya, CORRIENTES<br>Urraka</p>
<p>17/01/2015 en Salta Capi, SALTA<br>Juan Falú</p>
<p>17/01/2015 en Oberá, MISIONES<br>Carlos Balmaceda</p>
<p>18/01/2015 en Alem, MISIONES<br>Carlos Balmaceda</p>
<p>18/01/2015 en Iguazú, MISIONES<br>Mariana Baraj</p>
<p>18/01/2015 en Corrientes Capi, CORRIENTES<br>Urraka</p>
            <br>
            <br>
            <h3>TALLERES</h3>
            <br>
            <p>17-18 y 30/01/2015 en Montecarlo, MISIONES<br>Taller de Myriam Sosa<br> Taller de Vera Goldman. MDT.</p>

            <br>
            <br>
            <h3>CULTURA E INFANCIA</h3>
            <br>

<p>7/01/2015 en Montecarlo, MISIONES<br>Arriba los humanos</p>
<p>8/01/2015 en Santo Pipo, MISIONES<br>Arriba los humanos</p>
<p>9/01/2015 en Oberá, MISIONES<br>Arriba los humanos</p>
<p>10/01/2015 en Aristóbulo del valle, MISIONES<br>Omar Holz</p>
<p>10/01/2015 en Corrientes (Capital), CORRIENTES<br>Arriba los humanos</p>
<p>10/01/2015 en Roldan, SANTA FE<br>Circo alboroto</p>
<p>11/01/2015 en Perugorría, CORRIENTES<br>Arriba los humanos</p>
<p>11/01/2015 en Puerto Gral. San Martín, SANTA FE<br>Arturello</p>
<p>11/01/2015 en Alem, MISIONES<br></p>
<p>12/01/2015 en Curuzu Cuatia, CORRIENTES<br>Arriba los humanos</p>
<p>12/01/2015 en San Vicente, MISIONES<br>Omar Holz</p>
<p>13/01/2015 en Granadero Baigorria, SANTA FE<br>Arturello</p>
<p>14/01/2015 en Lavalle, MENDOZA<br>Arriba los humanos</p>
<p>14/01/2015 en Palpala, JUJUY<br>CircoPate</p>
<p>15/01/2015 en San Pedro, JUJUY<br>CircoPate</p>
<p>16/01/2015 en El Trébol, SANTA FE<br>Quique di Mauro</p>
<p>17/01/2015 en San José, ENTRE RÍOS<br>Circo alboroto</p>
<p>17/01/2015 en Las parejas, SANTA FE<br>Quique di Mauro</p>
<p>18/01/2015 en Venado Tuerto, SANTA FE<br>Quique di Mauro</p>
<p>20/01/2015 en SANTA FE<br>Circo alboroto</p>
        </div><!--descripcionLug-->
    </div>
<?php
/*
 * 
 * 
 * mardelplata
 * 
 * 
 */


} else if ($this->data['idactividad'] == 'mardelplata') { ?>
    <div id="bgLug" class="bgLug btnFullImg" style="background: url('/img/bg_green.jpg') fixed" >

        <div id="closeLug" class="closeLug"></div>
        <div id="nombreLug" class="nombreLug ">
            <p>MAR DEL PLATA (Base Naval de Mar del Plata – Av. Martinez de Hoz s/n), del 14 enero al 23 de febrero, de miércoles a domingo de 16 a 24 hs.
            <br><strong>Entrada libre y gratuita</strong></p>
        </div>
        
        <div id="descripcionLug" class="descripcionLug"><p>La Base Naval de la ciudad de Mar del Plata será un destino imperdible donde vas a poder recorrer con entrada libre y gratuita el buque escuela de la Armada Argentina Fragata Libertad, conocer el Parque de Dinosaurios con más de 30 especies de dinosaurios animatrónicos, visitar la Feria de comidas y artesanos, la Muestra de Paleontología, el Parque ECO, la Feria de emprendedores, la Kermes de Pakapaka y la Muestra de fotos.<br> También vas a poder disfrutar de programas como Ajedrecear, Hacelo Sonar, Café Cultura, Maravillosa Música, Tango de mis Amores conmemorando el año Gardeliano, Chocolate Cultura, Alta Fogata /Tablas, Tienda Matra, Jornadas Argentinas de Humor. Vas a poder participar de juegos interactivos de turismo, de una obra de teatro, y tomarte una fotografía en el destino de Argentina que elijas, así como ver la historieta más larga del mundo y muchas más actividades.
            </p>
        </div>
        
        <div id="agendaLug" class="agendaLug">
            <p><strong>Enero:</strong><br />
  14/01 LA MOSCA / URRAKA <br />
  15/01 LOS DEL FUEGO <br />
  16/01 JAVIER RODRÍGUEZ Y NOELIA BARSI / SEXTETO MAYOR<br />
  17/01 BERSUIT <br />
  18/01 REGGAE SUR / EL CHOQUE URBANO<br />
  22/01 LOS CAFRES <br />
  23/01 DIEGO AMORIN Y CECILIA CAPELLO / ORQUESTA TÍPICA RASCACIELOS<br />
  24/01 ESTUDIANTES DEL INTERIOR / LA MANCHA DE ROLANDO / LA PIPETUA<br />
  25/01 HORA LIBRE<br />
  28/01 FESTIVAL DE CUARTETO<br />
  29/01 TOTOTOMAS / EXCURSIONES POLARES / ONDA VAGA<br />
  30/01 INÉS MUZOPAPPA Y ALEJANDRO HERMIDA / ORQUESTA TÍPICA FERNÁNDEZ FIERRO<br />
  31/01 LA POSTAL / AGARRATE CATALINA</p><br>
        
            <p><strong>Febrero:</strong><br />
  01/02 CARNAVALE DI VENDETTA / LA FRANELA<br />
  05/02 KARAVANA / BRUNO ARIAS <br />
  06/02 EMMANUEL MARIN Y LEYLA ANTUNEZ / ORQUESTA TÍPICA JULIÁN PERALTA<br />
  07/02 IVAN NOBLE <br />
  08/02 LA PIPETUA / MISS BOLIVIA <br />
  11/02 SE TRATA DE NOSOTRAS<br />
  12/02 VETAMADRE / LOS PERICOS <br />
  13/02 CARLOS Y MARÍA RIVAROLA / ORQUESTA TÍPICA SANS SOUCI<br />
  14/02 HORA LIBRE / KAPANGA <br />
  15/02 LA BOMBA DE TIEMPO<br />
  18/02  CAD COMBINADO ARGENTINO DE DANZA/VICTOR HEREDIA, JAIRO, PEDRO AZNAR<br />
  19/2 CAD COMBINADO ARGENTINO DE DANZA/CIENTÍFICOS AL PALO <br />
  20/02 MILENA PLEBS Y ANDRÉS TANGUITO CEJAS / AMORES TANGO / TOQUE <br />
  21/02 TOQUE<br />
22/02 EL BORDO</p>

       </div><!--descripcionLug-->
    </div>
<?php
/*
 * 
 * ezeiza
 * 
 * 
 */
} else if ($this->data['idactividad'] == 'ezeiza') { ?>
    <div id="bgLug" class="bgLug btnFullImg" style="background: url('/img/bg_green.jpg') fixed" >

        <div id="closeLug" class="closeLug"></div>
        <div id="nombreLug" class="nombreLug ">
<p><strong>EZEIZA</strong> (Centro Recreativo Nacional de Ezeiza -  Autopista Ricchieri, bajada puente El Trébol, acceso Jorge Newbery), del  13 de enero al 28 de febrero, de martes a domingo de 9 a 21 hs.</p>
        </div>  
        
        <div id="descripcionLug" class="descripcionLug ">
<p>En los Bosques, con entrada libre y gratuita, podés encontrar muchísimas actividades al aire

libre: jugar al ajedrez, hacer tus propios instrumentos en Hacelo Sonar, escuchar a los chicos 

que participaron de Maravillosa Música y recorrer la Feria de comidas y emprendedores. 

Además, vas a encontrar un puesto de Atención primaria de salud y vas a poder Aprender 

Jugando, una propuesta entretenida y didáctica para acercar la matemática a los chicos.

Todo eso y mucho, pero mucho más.
</p>
        </div>
        
        
        <div id="agendaLug" class="agendaLug">
<p><strong>Enero:</strong><br />
  17/01 REGGAE SUR / LOS CAFRES<br />
  18/01 CIENTÍFICOS DEL PALO / LOS PERICOS<br />
  24/01 CARNAVALE DI VENDETTA / CAFUNDO / MISS BOLIVIA<br />
  25/01 ESTUDIANTES DEL INTERIOR / LOS YUPANQUI<br />
  31/01 LA FRANELA</p><br />
<p><strong>Febrero:</strong><br />
  01/02 KARAVANA / BRUNO ARIAS<br />
  07/02 URRAKA / VICTOR HEREDIA<br />
  08/02 TITA PRINT / LA MOSCA<br />
  14/02 BERSUIT / AGARRATE CATALINA <br />
  15/02 EL CHOQUE URBANO<br />
  21/02 TOQUE<br />
  22/02 VETAMADRE / LA MANCHA DE ROLANDO<br />
  28/02 EXCURSIONES POLARES / SHAMAN Y LOS PILARES DE LA CREACIÓN / ONDA VAGA</p>
       </div>
    </div><!--bgLug-->
<?php
} else if ($this->data['idactividad'] == 'sanrafael') { ?>
    <div id="bgLug" class="bgLug btnFullImg" style="background: url('/img/bg_green.jpg') fixed" >

        <div id="closeLug" class="closeLug"></div>
        <div id="nombreLug" class="nombreLug ">
            <p><strong>SAN RAFAEL, MENDOZA</strong> (Parque Hipólito Irigoyen de San Rafael), Del 10 de enero al 23 de febrero, de miércoles a domingo de 19 a 24 hs.
            </p>
        </div>        
        <div id="descripcionLug" class="descripcionLug ">
            <p>Este año, con entrada libre y gratuita, vas a poder recorrer la Muestra del Cuerpo humano que brinda conocimiento sobre el esqueleto  y los sistemas que componen el organismo, vas a poder jugar y aprender ajedrez con Ajedrecear, vas a poder hacer en tus propios instrumentos con Hacelo Sonar, ver los debates de Café Cultura, escuchar  a los chicos que participaron de Maravillosa Música, bailar con el Tango de mis Amores (Año Gardeliano), participar de Chocolate Cultura, Tienda Matra, recorrer la Feria de comidas y artesanos, la Muestra de fotos, y participar del Juego de preguntas y respuestas.
            </p>
        </div>
        <div id="agendaLug" class="agendaLug">
            <p><strong>Enero:</strong><br />
  10/01 RIMANDO ENTREVERSOS / MISS BOLIVIA<br />
  11/01 URRAKA<br />
  15/01 EL CHANGO SPASIUK <br />
  16/01 CARLOS Y MARÍA RIVAROLA / ORQUESTA TÍPICA ALMAGRO<br />
  17/01 KARAVANA / BRUNO ARIAS<br />
  18/01 ESTUDIANTES DEL INTERIOR / LA BOMBA DE TIEMPO<br />
  22/01 LOS HERMANOS CARABAJAL <br />
  23/01 MILENA PLEBS Y ANDRÉS TANGUITO CEJAS / ORQUESTA TÍPICA SANS SOUCI<br />
  24/01 EL BORDO<br />
  25/01 RIMANDO ENTREVERSOS / EL CHOQUE URBANO <br />
  29/01 CARNAVALE DI VENDETTA / LOS CAFRES<br />
  30/01 ROBERTO CASTILLO Y JULIETA BISCIONE / SEXTETO RAÚL GARELLO<br />
  31/01 REGGAE SUR / BERSUIT </p><br />
<p><strong>Febrero:</strong><br />
  01/02 TITA PRINT/CAFUNDO<br />
  05/02 LA MOSCA<br />
  06/02 INES MUZZOPAPPA Y ALEJANDRO HERMIDA / SEXTETO MAYOR<br />
  07/02 AGARRATE CATALINA <br />
  08/02 VICTOR HEREDIA <br />
  12/02 MARIANA PARAWAY / SHAMAN Y LOS PILARES DE LA CREACIÓN / ONDA VAGA <br />
  13/02 JAVIER RODRÍGUEZ Y NOELIA BARSI / ORQUESTA TÍPICA RASCACIELOS<br />
  14/02 LA MANCHA DE ROLANDO<br />
  15/02 IVAN NOBLE<br />
  19/02 VETAMADRE / LA FRANELA<br />
  18/02 SE TRATA DE NOSOTRAS<br />
  20/02 ANDRÉS LAZA MORENO Y LUCIANA ARREGUI / HEREDEROS DEL COMPÁS<br />
  21/02 TOQUE<br />
  22/02 CIENTÍFICOS DEL PALO </p>
       </div>
    </div><!--bgLug-->
<?php
} else if ($this->data['idactividad'] == 'sms') { ?>
    <div id="bgLug" class="bgLug btnFullImg" style="background: url('/img/bg_green.jpg') fixed" >

        <div id="closeLug" class="closeLug"></div>
        <div id="nombreLug" class="nombreLug">
            <p><strong>SAN MARCOS SIERRAS, CÓRDOBA </strong>(Polideportivo Municipal Humberto "el gringo" Casini - Libetad y el Jilguero), Del 10 de enero al 23 de febrero, de miércoles a domingo de 16 a 24 hs.
           </p>
        </div>
        <div id="descripcionLug" class="descripcionLug">
           <p>Con entrada libre y gratuita vas a poder  jugar al ajedrez en  Ajedrecear, hacer tus propios instrumentos con Hacelo Sonar, ver los debates de Café Cultura, bailar con Tango de mis Amores (Año Gardeliano). Vas a poder ser parte de Maravillosa Música, Chocolate Cultura, Tienda Matra, recorrer la Feria de comidas y artesanos, la muestra de fotos y la  Muestra de máscaras e indumentaria de pueblos originarios donde se presenta las materias primas utilizadas por los mocovíes, aimará o tehuelches en la confección de sus prendas.</p>
        </div>
        <div id="agendaLug" class="agendaLug">
            <p><strong>Enero:</strong><strong><u> </u></strong><br />
  10/01 ESTUDIANTES DEL INTERIOR / CIENTÍFICOS DEL PALO / LA BOMBA DE TIEMPO<br />
  11/01 YUPANQUIS<br />
  14/01 ARIADNA NAVEIRA Y FERNANDO SÁNCHEZ / ORQUESTA TÍPICA FERNANDEZ FIERRO<br />
  15/01 BRUNO ARIAS<br />
  16/01 SE TRATA DE NOSOTRAS<br />
  17/01 EL BORDO<br />
  21/01 INÉS MUZZOPAPPA Y ALEJANDRO HERMIDA / SEXTETO RAÚL GARELLO<br />
  22/01 DNI / VETAMADRE / BERSUIT<br />
  23/01 EL CHOQUE URBANO<br />
  24/01 RAIZ Y CANTO / EL CHANGO SPASIUK<br />
  25/01 HRASH / MISS BOLIVIA<br />
  28/01 ANDRÉS TANGUITO CEJAS Y GENOVEVA FERNÁNDEZ / SEXTETO MAYOR<br />
  29/01 KARAVANA / MARIANA BARAJ / LOS TEKIS / URRAKA<br />
  30/01 BANDA XXI<br />
  31/01 LOS HERMANOS CARABAJAL </p>
<p><strong>Febrero:</strong><br />
  01/02 LOS YUPANQUI<br />
  04/02 JAVIER RODRÍGUEZ Y NOELIA BARSI / ORQUESTA TÍPICA RASCACIELOS<br />
  05/02 LA MANCHA DE ROLANDO<br />
  07/02 ONDA VAGA / TOTOTOMAS / SHAMAN Y LOS PILARES DE LA CREACIÓN<br />
  08/02 AGARRATE CATALINA <br />
  11/02 GASTÓN TORELLI Y MOIRA CASTELLANOS / ORQUESTA TÍPICA ALMAGRO<br />
  12/02 CARNAVALE DI VENDETTA / LOS CAFRES<br />
  13/02 CAFUNDO <br />
  14/02 IVÁN NOBLE<br />
  18/02 DANA FRIGOLI Y ADRIÁN FERREYRA / ORQUESTA TÍPICA SANS SOUCI<br />
  19/02 LOS PERICOS<br />
  21/02 TOQUE<br />
  22/02 TITA PRINT / LA MOSCA</p>
        </div>
    </div><!--bgLug-->
<?php
} else if ($this->data['idactividad'] == 'lasgrutas') { ?>
    <div id="bgLug" class="bgLug btnFullImg" style="background: url('/img/bg_green.jpg') fixed" >

        <div id="closeLug" class="closeLug"></div>
        <div id="nombreLug" class="nombreLug ">
           <p>LAS GRUTAS, RÍO NEGRO (boulevard av. Int. Bresciano - calle Treneta y Yamine entre 4° y 3°), del 10 de enero al 23 de febrero, de miércoles a domingo de 16 a 24 hs. 
           <strong>Entrada libre y gratuita</strong></p>
        </div>
        <div id="descripcionLug" class="descripcionLug ">
           <p>Todo con entrada libre y gratuita, vas a poder jugar y aprender ajedrez con Ajedrecear, hacer  tus propios instrumentos con Hacelo Sonar, ver los debates de Café Cultura, bailar con el Tango de mis Amores (Año Gardeliano), escuchar a los chicos que participaron de Maravillosa Música, recorrer Tienda Matra, la Feria de comidas y artesanos, y la muestra de fotos. También habrá para los chicos Juegos y Chocolate Cultura.</p>
        </div>
        
        
        <div id="agendaLug" class="agendaLug">
            <p><strong>Enero:</strong><br />
  11/01 D5 / IVÁN NOBLE <br />
  15/01 LA PARTUSA / LOS CAFRES<br />
  16/01 MILENA PLEBS Y ANDRÉS TANGUITO CEJAS / ORQUESTA TÍPICA RASCACIELOS <br />
  17/01 EL CHANGO SPASIUK<br />
  18/01 KAPANGA <br />
  22/01 LOS PERICOS<br />
  23/01 GASTÓN TORELLI Y MOIRA CASTELLANOS / ORQUESTA TÍPICA FERNANDEZ FIERRO<br />
  24/01 KARAVANA / BRUNO ARIAS<br />
  29/01 BERSUIT<br />
  30/01 JAVIER RODRIGUEZ Y NOELIA BARSI / ORQUESTA TÍPICA SANS SOUCI<br />
  31/01 VETAMADRE / GÉNERO / EL BORDO</p>
<p><strong>Febrero:</strong><br />
  01/02 AGARRATE CATALINA<br />
  05/02 CARNAVALE DI VENDETTA / SHAMAN Y LOS PILARES DE LA CREACIÓN / EXCURSIONES POLARES / ONDA VAGA<br />
  06/02 ROBERTO CASTILLO Y JULIETA BISCIONE / SEXTETO RAÚL GARELLO<br />
  07/02 LA MANCHA DE ROLANDO<br />
  08/02 LOS DEL FUEGO <br />
  12/02 CIENTÍFICOS DEL PALO / LA FRANELA<br />
  13/02 INÉS MUZZOPAPPA Y ALEJANDRO HERMIDA / SEXTETO MAYOR<br />
  14/02 TITA PRINT / URRAKA<br />
  15/02 GIOVANI Y SU BANDA / VICTOR HEREDIA <br />
  19/02 LA MOSCA <br />
  20/02 CARLOS Y MARÍA RIVAROLA / ORQUESTA TÍPICA ALMAGRO<br />
  21/02 TOQUE<br />
  22/02 MISS BOLIVIA </p>
           
        </div>
    </div><!--bgLug-->
<?php
} else if ($this->data['idactividad'] == 'plano-mardelplata') { ?>
    <div id="bgLug" class="bgLug btnFullImg" style="background: url('/img/bg_green.jpg') fixed" >
        <div id="closeLug" class="closeLug"></div>
        <div id="descripcionLug" class="planito"><img src='/img/<?php echo $this->data['idactividad'] ?>.png'></div>
        
    </div><!--bgLug-->
<?php
} else if ($this->data['idactividad'] == 'plano-sanrafael') { ?>
    <div id="bgLug" class="bgLug btnFullImg" style="background: url('/img/bg_green.jpg') fixed" >
        <div id="closeLug" class="closeLug"></div>
        <div id="descripcionLug" class="planito"><img src='/img/<?php echo $this->data['idactividad'] ?>.png'></div>

    </div><!--bgLug-->
<?php
} 
/*
 * <div id="bgLug" class="bgLug btnFullImg" data-ibg-bg="img/lugares/puntaEspinoza.jpg">
				<img class="cacheImg" src=""/>
 * 
 */
