<?php if ($this->data['idactividad']=='fiestas'){?>
<div id="bgLug" class="bgLug btnFullImg" data-ibg-bg="/img/bg_red.jpg">
				<div id="closeLug" class="closeLug"></div>
				<div id="nombreLug" class="nombreLug fullImgOcultar">Fiestas Nacionales</div>
				<div id="descripcionLug" class="descripcionLug fullImgOcultar">
					<p>Las Fiestas Nacionales son un reflejo de la esencia y la identidad de los pueblos de nuestro país, en las que participan las comunidades y fortalecen así la diversidad cultural de Argentina al reforzar las características propias de cada lugar.</p>

<p>Te presentamos el cronograma de las Fiestas Nacionales que este verano vas a poder disfrutar en todo el país: artesanías, automovilismo, corvinas, folclore, carnaval, chamamé, cebada, quesos, playas de río, pesca y mucho más. </p>
<p>Para seguir profundizando el camino de integración y acceso a las distintas expresiones culturales en todo nuestro territorio, nada mejor que tomar esta ruta cultural y disfrutar con alegría.</p>
<p>Este verano también podés emocionarte con las Fiestas Nacionales. Vení a disfrutar de tu país. Vení a un verano lleno de emociones</p>
</div><!--descripcionLug-->
			</div><!--bgLug-->
<?php } else { ?>
         <div id="bgLug" class="bgLug btnFullImg" data-ibg-bg="/img/bg_green.jpg" >
				
				<div id="closeLug" class="closeLug"></div>
                                <div style >	<div id="nombreLug" class="nombreLug ">Casas de la Historia y la Cultura del Bicentenario</div>
				<div id="descripcionLug" class="descripcionLug">
				<p>Las Casas de la Historia y la Cultura del Bicentenario abren sus puertas este verano, en más de 90 lugares del pais, con obras teatrales, espectáculos, música en vivo, propuestas audiovisuales, charlas debates con referentes de la cultura y talleres para toda la familia para que visite todo el público. 
                                    </p>
<p>Las Casas son lugares destinados al desarrollo de actividades culturales, educativas y recreativas creadas para que artistas y colectivos puedan fomentar sus proyectos culturales de las comunidades en donde están insertas.
    </p>
<p>Las actividades comienzan el 7 de enero y continúan hasta el 16 de febrero,  y son todas gratuitas.
</p><br>
<div style="padding:6px;background-color: darkslategray">
    <h3></h3>
    <div style=""></div>
    <div></div>
    <div></div>
</div>
       <!-- <table width="390px" cellpadding="0" cellspacing="0">
  <col width="65" span="5" />
  <tr>
    <td width="20%">9/10/01/15</td>
    <td width="20%">Santa Rosa&nbsp;</td>
    <td width="20%">LA PAMPA</td>
    <td width="20%">CAFE CULTURA</td>
    <td width="20%">Las Amaro</td>
  </tr>
  <tr>
    <td width="20%">8/1/15</td>
    <td width="20%">capital Santa Fe Cap</td>
    <td width="20%"></td>
    <td width="20%"></td>
    <td rowspan="2" width="20%">Los Hermanos Queridos - Obra Teatral (Norberto   Gonzalo)</td>
  </tr>
  <tr>
    <td width="20%">9/1/15</td>
    <td width="20%"></td>
    <td width="20%">SANTA FE</td>
    <td width="20%">CAFE CULTURA</td>
  </tr>
  <tr>
    <td width="20%">18-19/01/2015</td>
    <td width="20%">Capital Federal</td>
    <td width="20%">NECOCHEA</td>
    <td width="20%">&nbsp;CAFE CULTURA&nbsp;</td>
    <td width="20%">Los Hermanos Queridos - Obra Teatral (Norberto Gonzalo)</td>
  </tr>
  <tr>
    <td width="20%">24/01/2015</td>
    <td width="20%">Capital Federal</td>
    <td width="20%">BUENOS AIRES</td>
    <td width="20%">&nbsp;CAFE CULTURA&nbsp;</td>
    <td width="20%">Los Hermanos Queridos - Obra Teatral (Norberto Gonzalo)</td>
  </tr>
  <tr>
    <td width="20%">10/1/15</td>
    <td width="20%">El Trebol</td>
    <td width="20%">SANTA FE</td>
    <td width="20%">CAFE CULTURA</td>
    <td width="20%">Los Hermanos Queridos - Obra Teatral (Norberto Gonzalo)</td>
  </tr>
  <tr>
    <td width="20%">11/1/15</td>
    <td width="20%">Venado tuerto</td>
    <td width="20%">SANTA FE</td>
    <td width="20%">CAFE CULTURA</td>
    <td width="20%">Los Hermanos Queridos - Obra Teatral (Norberto Gonzalo)</td>
  </tr>
  <tr>
    <td width="20%">16/01/2015</td>
    <td width="20%">Curuzu Cuatia</td>
    <td width="20%">CORRIENTES</td>
    <td width="20%">CAFE CULTURA</td>
    <td width="20%">Urraka</td>
  </tr>
  <tr>
    <td width="20%">16/01/2015</td>
    <td width="20%">San Vicente</td>
    <td width="20%">MISIONES</td>
    <td width="20%">CAFE CULTURA</td>
    <td width="20%">Carlos Balmaceda</td>
  </tr>
  <tr>
    <td width="20%">16/01/2015</td>
    <td width="20%">San Salvador de Jujuy</td>
    <td width="20%">JUJUY</td>
    <td width="20%">CAFE CULTURA</td>
    <td width="20%">Juan Falu</td>
  </tr>
  <tr>
    <td width="20%">16/ 17/01/2015</td>
    <td width="20%">Santo Pipo</td>
    <td width="20%">MISIONES</td>
    <td width="20%">CAFE CULTURA</td>
    <td width="20%">Mariana Baraj</td>
  </tr>
  <tr>
    <td width="20%">17/01/2015</td>
    <td width="20%">Goya</td>
    <td width="20%">CORRIENTES</td>
    <td width="20%">CAFE CULTURA</td>
    <td width="20%">Urraka</td>
  </tr>
  <tr>
    <td width="20%">17/01/2015</td>
    <td width="20%">Salta Capi</td>
    <td width="20%">SALTA</td>
    <td width="20%">CAFE CULTURA</td>
    <td width="20%">Juan Falu</td>
  </tr>
  <tr>
    <td width="20%">17/01/2015</td>
    <td width="20%">Oberá</td>
    <td width="20%">MISIONES</td>
    <td width="20%">CAFE CULTURA</td>
    <td width="20%">Carlos Balmaceda</td>
  </tr>
  <tr>
    <td width="20%">18/01/2015</td>
    <td width="20%">Alem</td>
    <td width="20%">MISIONES</td>
    <td width="20%">CAFE CULTURA</td>
    <td width="20%">Carlos Balmaceda</td>
  </tr>
  <tr>
    <td width="20%">18/01/2015</td>
    <td width="20%">Iguazú</td>
    <td width="20%">MISIONES</td>
    <td width="20%">CAFE CULTURA&nbsp;</td>
    <td width="20%">Mariana Baraj</td>
  </tr>
  <tr>
    <td width="20%">18/01/2015</td>
    <td width="20%">Corrientes Capi</td>
    <td width="20%">CORRIENTES</td>
    <td width="20%">CAFE CULTURA</td>
    <td width="20%">Urraka</td>
  </tr>
  <tr>
    <td width="20%">17/18/01/2015// 30/01/2015&nbsp;</td>
    <td width="20%">Montecarlo&nbsp;</td>
    <td width="20%">Misiones&nbsp;</td>
    <td width="20%">Taller de Myriam Sosa / Taller de Vera Goldman.</td>
    <td width="20%">Taller de Myriam Sosa// Taller de Vera Goldman. MDT.</td>
  </tr>
  <tr>
    <td width="20%">7/1/14</td>
    <td width="20%">Misiones // Montecarlo</td>
    <td width="20%">Misiones&nbsp;</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">arriba los humanos</td>
  </tr>
  <tr>
    <td width="20%">8/1/14</td>
    <td width="20%">Misiones // Santo Pipo</td>
    <td width="20%">Misiones&nbsp;</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">arriba los humanos</td>
  </tr>
  <tr>
    <td width="20%">9/1/14</td>
    <td width="20%">Misiones // Obera</td>
    <td width="20%">Misiones&nbsp;</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">arriba los humanos</td>
  </tr>
  <tr>
    <td width="20%">10/1/14</td>
    <td width="20%">Misiones // Aristóbulo del valle</td>
    <td width="20%">Misiones&nbsp;</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">Omar Holz</td>
  </tr>
  <tr>
    <td width="20%">10/1/15</td>
    <td width="20%">Corrientes (Capital)</td>
    <td width="20%">Corrientes</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">arriba los humanos</td>
  </tr>
  <tr>
    <td width="20%">10/1/14</td>
    <td width="20%">Santa Fe // Roldan</td>
    <td width="20%">Santa Fe</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">Circo alboroto</td>
  </tr>
  <tr>
    <td width="20%">11/01/2015 (ok)</td>
    <td width="20%">Corrientes // Perugorria</td>
    <td width="20%">Corrientes</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">arriba los humanos</td>
  </tr>
  <tr>
    <td width="20%">11/1/14</td>
    <td width="20%">Santa Fe / Puerto Gral. San Martín</td>
    <td width="20%">Santa Fe</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">Arturello</td>
  </tr>
  <tr>
    <td width="20%">11/1/14</td>
    <td width="20%">Misiones // Alem</td>
    <td width="20%">Misiones</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%"></td>
  </tr>
  <tr>
    <td width="20%">12/01/2015 (ok)</td>
    <td width="20%">Corrientes // Curuzu Cuatia</td>
    <td width="20%">Corrientes</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">arriba los humanos</td>
  </tr>
  <tr>
    <td width="20%">12/1/14</td>
    <td width="20%">Misiones // San Vicente</td>
    <td width="20%">Misiones</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">Omar Holz</td>
  </tr>
  <tr>
    <td width="20%">13/01/2014</td>
    <td width="20%">Santa Fe // Granadero Baigorria</td>
    <td width="20%">Santa Fe</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">Arturello</td>
  </tr>
  <tr>
    <td width="20%">14/01/2014</td>
    <td width="20%">Mendoza // Lavalle</td>
    <td width="20%">Mendoza</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">arriba los humanos</td>
  </tr>
  <tr>
    <td width="20%">14/01/2014</td>
    <td width="20%">Jujuy // Palpala</td>
    <td width="20%">Jujuy</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">CircoPate ( Sebastián )</td>
  </tr>
  <tr>
    <td width="20%">15/01/2014</td>
    <td width="20%">Jujuy // San Pedro</td>
    <td width="20%">Jujuy</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">CircoPate ( Sebastián )</td>
  </tr>
  <tr>
    <td width="20%">16/01/2014</td>
    <td width="20%">Santa Fe // El trébol</td>
    <td width="20%">Santa Fe</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">Quique di mauro</td>
  </tr>
  <tr>
    <td width="20%">17/01/2014</td>
    <td width="20%">Entre Ríos // San José</td>
    <td width="20%">Entre Ríos</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">Circo alboroto</td>
  </tr>
  <tr>
    <td width="20%">17/01/2014</td>
    <td width="20%">Santa fe // Las parejas</td>
    <td width="20%">Santa Fe</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">Quique di mauro</td>
  </tr>
  <tr>
    <td width="20%">18/01/2014</td>
    <td width="20%">Santa Fe // Venado Tuerto</td>
    <td width="20%">Santa Fe</td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">Quique di mauro</td>
  </tr>
  <tr>
    <td width="20%">20/01/2014</td>
    <td width="20%">Santa Fe // Santa Fe</td>
    <td width="20%"></td>
    <td width="20%">CULTURA E INFANCIA</td>
    <td width="20%">Circo alboroto</td>
  </tr>
</table>   -->                      
                                </div>
                                </div><!--descripcionLug-->
			</div><!--bgLug-->               
                        
<?php }
/*
 * <div id="bgLug" class="bgLug btnFullImg" data-ibg-bg="img/lugares/puntaEspinoza.jpg">
				<img class="cacheImg" src=""/>
 * 
 */
