<?php 

$contenido = array(
    1 => array (
        'id' => 'mardelplata',
        'plano' => 'si',
        'btn' => 'agenda-mardelplata',
        'bg1' => 'rp-mdq-02.jpg',
        'bg2' => 'rp-mdq-01.jpg',
        'titulo' => 'Disfrutá de <b>Mar del Plata</b>',
        'dire' => 'Base Naval de Mar del Plata <br>Av. Martinez de Hoz s/n. <br>Desde el 14 de enero al 23 de febrero, de miércoles a domingo de 16 a 24 hs.',
        'contenido' => '
            <p>La Rambla, el Torreón, los lobos marinos, los cornalitos en el puerto, los alfajores, los boliches de Constitución.</p>
<p>Este verano además de lo que hacés todos los años, en Mar del Plata vas a poder ir a recitales, recorrer la Fragata Libertad, ver dinosaurios, jugar ajedrez, fabricar tus propios instrumentos, bailar tango y probar comidas típicas de todo el país, entre otras muchas cosas.</p>
<p>Para seguir profundizando el camino de integración y acceso a las distintas expresiones culturales en todo nuestro territorio, nada mejor que tomar esta ruta cultural y disfrutar con alegría. </p>
<p>Este verano vas a emocionarte como nunca.  Vení a disfrutar de  Mar del Plata. Vení a disfrutar de tu país. Vení a un verano lleno de emociones.</p>',
        'info' => '<h5>Actividades Mar del Plata</h5>
<p>(Base Naval de Mar del Plata – Av. Martinez de Hoz s/n. Desde el 14 de enero al 23 de febrero)</p>
<p>Buque escuela de la Armada Argentina Fragata Libertad, Parque de Dinosaurios, Ajedrecear, Hacelo Sonar, Café Cultura, Tango de mis Amores (Año Gardeliano), Chocolate Cultura, Alta Fogata / Tablas, 
Tienda Matra, Jornadas Argentinas de Humor, Feria de comidas y artesanos, Muestra de Paleontología, 
Parque ECO, Feria de emprendedores, Kermes de Pakapaka, Muestra de fotos.</p>',
        
    ),
    2 => array (
        'id' => 'ezeiza',
        'plano' => 'no',
        'btn' => 'agenda-ezeiza',
        'bg1' => 'rp-eze-02.jpg',
        'bg2' => 'rp-eze-01.jpg',
        'titulo' => 'Divertite en Los Bosques de Ezeiza',
        'dire' => 'Centro Recreativo Nacional de Ezeiza - Autopista Ricchieri, bajada puente El Trébol, acceso Jorge Newbery. <br>

Desde el 13 de enero al 28 de febrero, de martes a domingo de 9 a 21 hs.',
        'contenido' => '
            <p>Los asados, los amigos, los picaditos, la lona en el pasto, los sandwiches de milanesa, los
mates de la tarde.
Este verano, además de todo lo que tienen Los Bosques de Ezeiza para que disfrutes, vas a 
poder ver recitales, probar platos típicos de todo el país, aprender jugando y aprovechar los 
puestos de hidratación.
Para seguir profundizando el camino de integración y acceso a las distintas expresiones 
culturales en todo nuestro territorio, nada mejor que tomar esta ruta cultural y disfrutar con 
alegría.
Este verano vas a emocionarte como nunca. Vení a divertirte en Los Bosques de Ezeiza. Vení 
a disfrutar de tu país. Vení a un verano lleno de emociones.</p>
            ',
        'info' => '<p>Centro Recreativo Nacional de Ezeiza - Autopista Ricchieri, bajada puente El Trébol, acceso Jorge Newbery

Desde el 13 de enero al 28 de febrero, de martes a domingo de 9 a 21 hs.</p>'
        . '',
        
    ),
    3 => array (
        'id' => 'sanrafael',
        'plano' => 'si',
        'btn' => 'agenda-sanrafael',
        'bg1' => 'rp-sr-02.jpg',
        'bg2' => 'rp-sr-01.jpg',
        'titulo' => 'Conocé San Rafael',
        'dire' => 'Parque Hipólito Irigoyen de San Rafael. <br>Desde el 10 de enero al 23 de febrero, de miércoles a domingo de 16 a 24 hs.',
        'contenido' => '
            <p>Las cabalgatas, el rafting, los asados, el kayak, las bodegas, las caminatas.</p>
<p>Este verano, además de todo lo que haces todos los años, en San Rafael vas a poder ver recitales, jugar ajedrez, ver una muestra del cuerpo humano, bailar tango, fabricar tus propios instrumentos, probar platos típicos de todo el país y ver el trabajo de los artesanos locales.</p>
<p>Para seguir profundizando el camino de integración y acceso a las distintas expresiones culturales en todo nuestro territorio, nada mejor que tomar esta ruta cultural y disfrutar con alegría. </p>
<p>Este verano vas a emocionarte como nunca.  Vení a conocer San Rafael. Vení a disfrutar de tu país. Vení a un verano lleno de emociones. </p>
            ',
        'info' => '<p>Parque Hipólito Irigoyen de San Rafael. Desde el 10 de enero al 23 de febrero, de miércoles a domingo de 16 a 24 hs.</p>'
        . '',
        
    ),
    4 => array (
        'id' => 'sms',
        'plano' => 'no',
        'btn' => 'agenda-sms',
        'bg1' => 'rp-sms-02.jpg',
        'bg2' => 'rp-sms-01.jpg',
        'titulo' => 'Relajate en San Marcos Sierras',
        'dire' => 'Polideportivo Municipal Humberto "el gringo" Casini - Libetad y el Jilguero. <br>Del 10 de enero al 23 de febrero, de miércoles a domingo de 16 a 24 hs.
',
        'contenido' => '
            <p>Las caminatas, el aire puro, las picadas, las artesanías, los alfajores, el museo hippie, la naturaleza, las quebradas y los ríos.</p>  
<p>Este verano, además de lo que disfrutás todos los años, en San Marcos Sierras vas a poder ir a recitales, jugar ajedrez, fabricar tus propios instrumentos, bailar tango, ver una muestra de máscaras y probar comidas típicas de todo el país, entre otras muchas cosas.</p>
<p>Para seguir profundizando el camino de integración y acceso a las distintas expresiones culturales en todo nuestro territorio, nada mejor que tomar esta ruta cultural y disfrutar con alegría. </p>
<p>Este verano vas a emocionarte como nunca.  Vení a relajarte en San Marcos Sierras. Vení a disfrutar de tu país. Vení a un verano lleno de emociones.</p>
            ',
        'info' => '<p>Polideportivo Municipal Humberto "el gringo" Casini - Libetad y el Jilguero. Del 10 de enero al 23 de febrero, de miércoles a domingo de 16 a 24 hs.
</p>'
        . '',
        
    ),
    5 => array (
        'id' => 'lasgrutas',
        'plano' => 'no',
        'btn' => 'agenda-lasgrutas',
        'bg1' => 'rp-grutas-02.jpg',
        'bg2' => 'rp-grutas-01.jpg',
        'titulo' => 'Descubrí Las Grutas',
        'dire' => 'Boulevard av. Int. Bresciano - calle Treneta y Yamine entre 4° y 3°. <br>Desde el 10 de enero al 23 de febrero, de miércoles a domingo de 16 a 24 hs',
        'contenido' => '
            <p>Los chapuzones, los campings, la pesca, los asados, los loros barranqueros, las mareas pronunciadas, los atardeceres en la playa.</p>
<p>Este verano, además de lo que hacés todos los años, en Las Grutas vas a poder ver recitales, jugar ajedrez, fabricar tus propios instrumentos, bailar tango, probar comidas típicas de todo el país,  recorrer la feria de artesanos, ver muestras de fotos y mucho más.</p>
<p>Para seguir profundizando el camino de integración y acceso a las distintas expresiones culturales en todo nuestro territorio, nada mejor que tomar esta ruta cultural y disfrutar con alegría. </p>
<p>Este verano vas a emocionarte como nunca.  Vení a descubrir Las Grutas. Vení a disfrutar de  tu país. Vení a un verano lleno de emociones</p>

',
        'info' => '<p>Boulevard av. Int. Bresciano - calle Treneta y Yamine entre 4° y 3°.  

Desde el 10 de enero al 23 de febrero, de miércoles a domingo de 16 a 24 hs</p>'
        . '',
        
    ),
);
?>

<?php  echo $this->data['id'] ?>
<div class="bg1" style="background-image: url(img/<?php  echo $contenido[$this->data['id']]['bg1'] ?>);"></div>
<div class="bg2" style="background-image: url(img/<?php  echo $contenido[$this->data['id']]['bg2'] ?>); display: block"></div>
<div class="cExtra">
    <div class="contenido">

        <div class="areaBtnStreet">
            <?php if ($contenido[$this->data['id']]['plano']=='si'){?>
                <div class="btnStreet btnActividades" target="_blank" data-idactividad="plano-<?php echo $contenido[$this->data['id']]['id'] ?>">
            <?php } else { ?> <div class="btnStreet "> <?php } ?>
                    
                    <div class="icon"><img width="100%" src="img/pin_plano.png"/></div>
                       
                        <div class="clear"></div>
                        <div class="icStreetVertical"><?php  echo $contenido[$this->data['id']]['dire'] ?></div><!---->
                </div>
    </div>



        <div class="titular">
            <div class="span"><?php  echo $contenido[$this->data['id']]['titulo'] ?></div>
        </div><!--titular-->


        <div class="dataTxt">
            <?php  echo $contenido[$this->data['id']]['contenido'] ?>
        </div><!--dataTxt-->

        <!-- <div class="imgTop imgAuto" style="background-image: url(img/islas/isla-fernandina-3.jpg);"></div>
-->
        <div class="islaLugares">
            <div class="btnLugar btnActividades" data-idactividad="<?php echo $contenido[$this->data['id']]['id'] ?>" style="background-image: url('/img/<?php  echo $contenido[$this->data['id']]['btn'] ?>.jpg');">
                <img class="imgCache" src="/img/<?php  echo $contenido[$this->data['id']]['btn'] ?>.jpg">
                <span>Agenda</span>
            </div>
        </div>

        <div class="clear"></div>

        <div class="comentario">
            <div class="txt">
                <?php  //echo $contenido[$this->data['id']]['info'] ?>
                Vení a disfrutar de un Verano de Emociones.
            </div><!--txt-->
            <div class="clear"></div>
        </div><!--comentario-->

        <div class="clear"></div>


    </div><!--contenido-->
</div><!--cExtra-->
<script>
    
$('.btnActividades').click(function(event) {
    event.preventDefault();
  $('#loadingAjaxLug').fadeToggle(250);
  idActividad = $(this).data('idactividad');

  var postDataLug = 'idactividad=' + idActividad;

  $.ajax({
    type: 'POST',
    dataType: 'html',
    cache: true,
    url: '/ajax/actividades',
    data: postDataLug,
    success: function(htmlLug) {

        $('#areaLugares').html(htmlLug).hide().waitForImages(function() {
          $('#areaLugares').show();
          $('#loadingAjaxLug').fadeToggle(250);
$('body').addClass( "sinScroll" );
          //BG Img
          /*$(".bgLug").interactive_bg({
            strength: 25,
            scale: 1.05,
            animationSpeed: "100ms"
          });*/
          $(window).resize(function() {
            $(".bgLug > .ibg-bg").css({
              width: $(window).outerWidth(),
              height: $(window).outerHeight()
            });
          });
          $("#bgLug,#nombreLug,#descripcionLug").css('cursor', 'url(img/cursor.png),auto');
          
          $('#closeLug').click(function() {
            $('body').removeClass( "sinScroll" );
            $('#areaLugares').fadeOut(250, function() {
              $('#areaLugares').html('');
            });
            return false;
          });
          $('.btnFullImg').not('#closeLug').click(function() {
            $('.fullImgOcultar').fadeToggle();
          });
          //BG Img

        });

      } //success
  }); //ajax

});


    </script>