<div id="bgLug" class="bgLug btnFullImg"  style="background: url('/img/bg_red.jpg') fixed">
    <div id="closeLug" class="closeLug"></div>
    <div id="descripcionLug" class="descripcionLug" style="top:80px;width: 60%;">
        <img style="float:left; padding-right: 16px;" src="<?php echo $data->getImagen_url() ?>">

        <h4><?php echo $data->getTitle() ?></h4><br/>

        <?php echo $data->getBajada() ?>


    </div><!--descripcionLug-->
</div><!--bgLug-->