
<div id="bgLug" class="bgLug btnFullImg" data-ibg-bg="/img/bg_red.jpg">
				<div id="closeLug" class="closeLug"></div>
				<div id="nombreLug" class="nombreLug fullImgOcultar">Fiestas Populares</div>
				<div id="descripcionLug" class="descripcionLug fullImgOcultar">
					<p>Las Fiestas Nacionales son un reflejo de la esencia y la identidad de los pueblos de nuestro país, en las que participan las comunidades y fortalecen así la diversidad cultural de Argentina al reforzar las características propias de cada lugar.</p>

<p>Te presentamos el cronograma de las Fiestas Nacionales que este verano vas a poder disfrutar en todo el país: artesanías, automovilismo, corvinas, folclore, carnaval, chamamé, cebada, quesos, playas de río, pesca y mucho más. </p>
<p>Para seguir profundizando el camino de integración y acceso a las distintas expresiones culturales en todo nuestro territorio, nada mejor que tomar esta ruta cultural y disfrutar con alegría.</p>
<p>Este verano también podés emocionarte con las Fiestas Nacionales. Vení a disfrutar de tu país. Vení a un verano lleno de emociones</p>
</div><!--descripcionLug-->
			</div><!--bgLug-->