<?php echo $this->doctype(); ?>

<html lang="es">
    <head>

        <meta charset="utf-8">
        <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>
        <?php echo $this->headTitle('Verano de Emociones ')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                  ->headLink(array('rel' => 'icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->appendStylesheet($this->basePath() . '/css/style.css','only screen and (min-width: 900px)')
                ->appendStylesheet($this->basePath() . '/css/onecolumn.css','only screen and (max-width: 900px)')
                
                
                
               // ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                // ->appendStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
               // ->appendStylesheet($this->basePath() . '/css/theme.css')
               // ->appendStylesheet($this->basePath() . '/css/bootstrap-select.min.css')
               // ->appendStylesheet($this->basePath() . '/fuelux/css/fuelux.min.css')
        ?>

        <!-- Important Owl stylesheet -->
<link rel="stylesheet" href="/owl-carousel/owl.carousel.css">
 
<!-- Default Theme -->
<link rel="stylesheet" href="/owl-carousel/owl.theme.css">
<style>
    .captiono{    background:rgba(0,0,0,0.5);
    bottom: 4px;
    display: block;
    padding: 12px;
    position: absolute;
    width: 64%;}
    .caption{position:absolute;bottom:0%;left:0px;width:100%;display:block;background:rgba(0,0,0,0.5);color:#fff;padding:10px;font-size:2em;letter-spacing:0.1em;line-height:1.2;opacity:0;}
    
    .p2noticia .cap{
        float:left;
    }
    .noticap p {
    color: darkgray;
    font-size: 14px;
    margin-top: 8px;
}
    .noticap {
    float:right;
    width:280px;
}
    .noticap img{
    float:left;
    width:190px;
}

#page4 .txt1 a{
    color:snow;
}
</style>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->appendFile($this->basePath() . '/assets/jquery.min.js')
                ->appendFile($this->basePath() . '/assets/jquery.spritely.js')
                
         /*       ->appendFile($this->basePath() . '/js/jquery.min.js')
                //->appendFile($this->basePath() . '/js/jquery.validate.min.js')
                ->appendFile($this->basePath() . '/js/bootstrap.min.js')
                ->appendFile($this->basePath() . '/js/bootstrap-select.min.js')
                ->appendFile($this->basePath() . '/js/i18n/defaults-es_CL.js')
                ->appendFile($this->basePath() . '/fuelux/js/fuelux.min.js')
                ->appendFile($this->basePath() . '/fuelux/js/wizard.js')
                ->appendFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->appendFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
*/

        ;
        ?>
<!-- Include js plugin -->
<script src="/owl-carousel/owl.carousel.js"></script>

<script type="text/javascript">
		var salto=0;
		
		$(document).ready(function() {
			
			console.log('...');
			var miniAlto=700;
			var fullHeight = $(window).height();
			$('.fullAlto').css("min-height",fullHeight);
			$(".margenAlto").css("margin-top", fullHeight+"px");
				
			//fullAlto
			$(function(){
				var $window = $(window).on('resize', function(){
					var fullHeight = $(window).height();
					if(fullHeight<miniAlto){fullHeight=miniAlto;}
					$('.fullAlto').css("min-height",fullHeight);
					//$(".margenAlto").css("margin-top", fullHeight+"px");
				}).trigger('resize');
			});
			
		});
	</script>
    </head>
        <body>

            <?php echo $this->content; ?>
            

<script type="text/javascript" src="/assets/skrollr.min.js"></script>
<script type="text/javascript" src="/assets/jquery.transform2d.js"></script>
<script type="text/javascript" src="/assets/jquery.waitforimages.min.js"></script>
<script type="text/javascript" src="/assets/jquery.interactive_bg.js"></script>

<!--[if lt IE 9]>
<script type="text/javascript" src="js/skrollr.ie.min.js"></script>
<![endif]-->

<script type="text/javascript">
    
    

    $(document).ready(function() {
     
    $("#owl-noticias").owlCarousel({

        navigation:false,
        slideSpeed : 300,
        paginationSpeed : 400,
        singleItem:true

        // "singleItem:true" is a shortcut for:
        // items : 1,
        // itemsDesktop : false,
        // itemsDesktopSmall : false,
        // itemsTablet: false,
        // itemsMobile : false

        });
    
    $("#owl-institucional").owlCarousel({
        navigation:false,
        slideSpeed : 300,
        paginationSpeed : 400,
        singleItem:true
        });
    
     <?php 
     $array=array(
         array('tag'=>'destacadas'),
         array('tag'=>'recitales'),
         array('tag'=>'grafica'),
     );
     foreach ($array as $ele) { ?>
    $("#owl-<?php echo $ele['tag'] ?>").owlCarousel({
        autoPlay:true,
        navigation:false,
        pagination:false,
        autoHeight : true,
        transitionStyle:"fade",
        jsonPath : 'http://api.flickr.com/services/feeds/photos_public.gne?tags=<?php echo $ele['tag'] ?>&id=129741112@N06&lang=es-ar&format=json&jsoncallback=?',
        jsonSuccess : function(data){
                            var content = "";
                            for(var i in data["items"]){
                            var img = data["items"][i].media.m;
                            var alt = data["items"][i].title;
                            console.log(data["items"][i]);
                            content += "<div><div class='captiono'>" +alt+ "</div><img width='176' src='" +img+ "' alt='" +alt+ "'></div>";
                            }

                            $("#owl-<?php echo $ele['tag'] ?>").html(content);
                        }
    });

     <?php } ?>

          <?php /*
     $array2=array(
         array('tag'=>'grafica'),
     );
     foreach ($array2 as $ele) { ?>
    $("#owl-<?php echo $ele['tag'] ?>").owlCarousel({
        autoPlay:true,
        navigation:false,
        pagination:false,
        autoHeight : true,
        transitionStyle:"fade",
        jsonPath : 'http://api.flickr.com/services/feeds/photos_public.gne?tags=<?php echo $ele['tag'] ?>&id=129741112@N06&lang=es-ar&format=json&jsoncallback=?',
        jsonSuccess : function(data){
                            var content = "";
                            for(var i in data["items"]){
                            var img = data["items"][i].media.m;
                            var alt = data["items"][i].title;
                            console.log(data["items"][i]);
                            content += "<img width='176' src='" +img+ "' alt='" +alt+ "'>";
                            }

                            $("#owl-<?php echo $ele['tag'] ?>").html(content);
                        }
    });

     <?php } */ ?>
 
     
    });


	var sk;
	
	$(document).ready(function() {
		
		var miniAlto=600;
		var fullHeight = $(window).height();
		
		$('.saltarIntro').click(function(){
			console.log('skip');
			salto=1;
			$('.saltarIntro').remove();
			
			$('#loading').removeClass('loadingOut');
			$('#loading').slideDown(500,function(){
				$('#intro').remove();
			});
			
			$.ajax({
				type:'POST',
				dataType:'html',
				cache:true,
				url:'iniAjax.php',
				success:function(htmlAjax){
					
					setTimeout(function() {
						$(document).scrollTop(0);
					}, 100);
					
					$('#full').append(htmlAjax).waitForImages(function() {
						$('#full').show(0);
						document.body.style.overflow = 'auto';
						
						$('#loading').addClass('loadingOut');
						$('#loading').delay(350).slideUp(750,function(){
							$('#loading').remove();
							sk.refresh();
						});
						sk.refresh();
					});
					
				}//success
			});//ajax
		});
		
		//fullAlto
		$(function(){
			var $window = $(window).on('resize', function(){
				var fullHeight = $(window).height();
				if(fullHeight<miniAlto){fullHeight=miniAlto;}
				$('.fullAlto').css("min-height",fullHeight);
				//$(".margenAlto").css("margin-top", fullHeight+"px");
			}).trigger('resize');
		});
		
		//smoothWheel
		jQuery.extend(jQuery.easing, {
			easeOutQuint: function(x, t, b, c, d) {
				return c * ((t = t / d - 1) * t * t * t * t + 1) + b;
			}
		});
		var wheel = false,
		$docH = $(document).height() - $(window).height(),
		$scrollTop = $(window).scrollTop();
		$(window).bind('scroll', function() {
			if (wheel === false) {
				$scrollTop = $(this).scrollTop();
			}
		});
		$('.smoothWheel').bind('DOMMouseScroll mousewheel', function(e, delta) {
			delta = delta || -e.originalEvent.detail / 3 || e.originalEvent.wheelDelta / 120;
			wheel = true;
			$scrollTop = Math.min($docH, Math.max(0, parseInt($scrollTop - delta * 20)));
			$($.browser.webkit ? 'body' : 'html').stop().animate({
				scrollTop: $scrollTop + 'px'
			}, 2000, 'easeOutQuint', function() {
				wheel = false;
			});
			return false;
		});
		//smoothWheel
		
                if(!(/Android|iPhone|iPad|iPod|BlackBerry|Windows Phone/i).test(navigator.userAgent || navigator.vendor || window.opera)){
                    sk = skrollr.init({
			smoothScrolling:false,
			smoothScrollingDuration:200,
			forceHeight: false
                    });
                }
		//Scroll Anim
		
		
	});
	
	$(window).load(function(){
		console.log('. => es');
		
		setTimeout(function() {
			$(document).scrollTop(0);
		}, 100);
		
		if(salto==0){
			$('#loading').addClass('loadingOut');
			$('#loading').delay(350).slideUp(500,function(){
				//$('#loading').remove();
				console.log('pre ...');
				$.ajax({
					type:'POST',
					dataType:'html',
					cache:true,
					url:'iniAjax.php',
					success:function(htmlAjax){
						console.log('pre ok');
					}//success
				});//ajax
			});
		}
		
	});
$('.btnDespleDer').click(function() {
  $('#loadingAjax').fadeToggle(250);

  var idAjax = $(this).data('idajax');
  var postData = 'id=' + idAjax;

  $.ajax({
    type: 'POST',
    dataType: 'html',
    cache: true,
    url: '/ajax',
    data: postData,
    success: function(htmlLug) {

        $('#rightPage').html(htmlLug).hide().waitForImages(function() {
           $('#rightPage').show(0);

          //$('#page').addClass('pageOff');
          $('#page').css({
            transform: 'translateX(-800px)'
          });
          //$('#rightPage').addClass('rightPageOn');
          $('#rightPage').css({
            transform: 'translateX(0px)'
          });
          $('.ocultarDer').fadeToggle(500);
          $('#loadingAjax').fadeToggle(500);
          $('body').addClass('sinScroll');

          $('.imgData').remove();
        });

      } //success
  }); //ajax

});






    
$('.ocultarDer').click(function() {
  //$('#page').removeClass('pageOff');
  $('#page').css({
    transform: 'translateX(0px)'
  });
  //$('#rightPage').removeClass('rightPageOn');
  $('#rightPage').css({
    transform: 'translateX(800px)'
  });
  $('.ocultarDer').fadeOut(500, function() {
    $('body').removeClass('sinScroll');
    $('#page').removeAttr('style');
    /*$('#rightPage').fadeTo('fast',0,function(){
				$('#rightPage').html('');
			});*/
  });
  $('#rightPage').animate({
    scrollTop: $('body').offset().top
  }, 750);
  return false;
});


$('.btnMenu').click(function() {
    
  $('.btnMenu').toggleClass('actMenu');
  $('.ocultar').toggleClass('oculto');
  $('#menu').slideToggle(550);
  $('#menu .lang').toggle(500);
  $('#menu .iz').fadeToggle(500);
  
});


$('.link').click(function() {
  var getIdLink = $(this).data('ancla');
  $('html, body').animate({
    scrollTop: $('#page' + getIdLink).offset().top
  }, 1000);
  $('.btnMenu').toggleClass('actMenu');
  $('.ocultar').toggleClass('oculto');
  $('#menu').slideToggle(550);
  $('#menu .lang').toggle(500);
  $('#menu .iz').fadeToggle(500);
  return false;
});
var fullAlto = 900;
$('#rightPage').scroll(function(e) {
  scrollRightPage = ($('.rightPage').scrollTop());
  $('.bg1, .bg2').css({
    top: scrollRightPage + 'px'
  });
  if (fullAlto > 850) {
    if (scrollRightPage > 100) {
      $('.bg2').fadeOut(500);
    } else {
      $('.bg2').fadeIn(500);
    }
  } else {
    if (scrollRightPage > 250) {
      $('.bg2').fadeOut(500);
    } else {
      $('.bg2').fadeIn(500);
    }
  }
});
</script>
	    
    </body>
</html>
