<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Listado de Usuarios</h3>
	</div>
<?php if ($this->isAllowed('usuarios', 'crear')) { ?> 
	<div class="toolbardt"><a class="btn btn-success" href="/usuarios/crear">
	<span class="glyphicon glyphicon-list-alt"></span> Nuevo</a></div>
<?php } ?>


<table class="table table-hover">
<tr>
    <th>ID</th>
    <th>Título</th>
    <th>FechaCreación</th>
    <th>&nbsp;</th>
</tr>
<?php $this->partialloop()->setObjectKey('noticias');
echo $this->partialloop('/partial/rowNoticia.phtml', $this->noticias) ?>
</table>

<?php  echo ( count($this->noticias) > 0 ) ? $this->paginationControl($this->noticias, 'Sliding', 'pager.phtml', array('lang'=>$lang, 'controller'=>'listar-noticias')) : ""; ?>
</div>
<script type="text/javascript">
	$(document).ready(function() {
	$(".fancybox").fancybox();
	});
</script>