
<div id="full" class="full" ondragstart="return false" style="">
	
	<!--loading-->
	
	<div id="loadingAjax" class="loadingAjax" style="display: none;">
		<div class="clLoading"></div>
	</div><!--loadingAjax-->
	
	<div id="loadingAjaxLug" class="loadingAjaxLug">
		<div class="clLoading"></div>
	</div><!--loadingAjaxLug-->
	
	<!--intro-->
	
	
	

<div class="btnFrameClose ocultarDer" style="display: none;">
	<div class="rf r1"></div>
	<div class="rf r2"></div>
	<div class="rf r3"></div>
</div><!--btnMenu-->

<div class="frameClose ocultarDer" style="display: none;"></div>

<div id="page" class="page smoothWheel">
	
	<div id="btnMenu" class="btnMenu">
		<div class="rf r1"></div>
		<div class="rf r2"></div>
		<div class="rf r3"></div>
	</div><!--btnMenu-->
	
	<div id="menu" class="menu">
		<?php echo $this->partial('menu.phtml') // <-- Add this!! ?>
    
	</div><!--menu-->
        
	<div id="page1" class="section pInicio fullAlto skrollable ">
            <div class="pInicioImg fullAlto ocultar skrollable  " data-0="background-position:0 20px;" data-700="background-position:0 -500px;" >
                 
                                <!-- <img src="/img/tipitos.png"> -->
            </div>
                
		
            <div class="txt1 ocultar skrollable " data-0="margin-top:-50px;" data-500="margin-top:100px;">
                
			<div id="conteBajar" class="conteBajar">
				
                            <div class="ic1">
                                <div style="height:80px">Scrollea para navegar</div>
                            </div>
                       <div class="ic2"><img src="/img/scrollico.png"></div>
			</div><!--conteBajar-->
		</div><!--txt1-->
                <div class="cucarda ocultar skrollable" data-500="top:1% ; left:0%;" data-600="top:1% ; left:-85%;" >
			<div style="height:68px; padding:9px 4px 0 90px">
				<img width="520" src="/img/logos.png">
			</div><!--btnReq-->
			<div class="clear"></div>
		</div>
          <style>
         .cucarda    {background: none repeat scroll 0 0 rgba(250, 250, 250, 0.8);
    border-bottom-left-radius: 2px;
    border-top-left-radius: 2px;
    display: block;
    position: fixed;
    left:0;
    right: 0;
    width: 630px;
    z-index: 3;}
        </style>
	</div><!--inicio-->
	
	<div id="page2" class="section pCamino fullAlto" style="background: url('/img/p2-bg-<?php  echo $this->imgnrand ?>.jpg') no-repeat scroll center center / cover rgba(0, 0, 0, 0); ">
		<div class="titular ocultar skrollable " data-500-top="top: 80px" data-250-top="top: 45px" >
                    <?php
                                switch($this->imgnrand){
                                    case 1 : echo 'Disfrutá de Mar del Plata';
                                        break;
                                    case 2 : echo 'Divertite en <br>los Piletones de Ezeiza';
                                        break;
                                    case 3 : echo 'Conocé San Rafael';
                                        break;
                                    case 4 : echo 'Relajate en <br>San Marcos Sierras';
                                        break;
                                    case 5 : echo 'Descubrí Las Grutas';
                                        break;
                                    
                                }
                                
                                ?></div>
		<div class="areaInfo ocultar skrollable " data-750-top="width:35%;" data-450-top="width:45%;">
			<div class="caminoInfo">
				

    <div id="owl-demo" class="owl-carousel">
    </div>

<?php  // echo $this->imgnrand ?>
				
			</div><!--caminoInfo-->
			<div class="clear"></div>
		</div><!--areaInfo-->
		<div class="areaRequerimiento ocultar skrollable skrollable-before" data-700-top="width:35%;" data-500-top="width:40%;">
			<div class="btnReq">
                            <span>
                                <?php
                                switch($this->imgnrand){
                                    case 1 : echo 'Mar del Plata';
                                        break;
                                    case 2 : echo 'Ezeiza';
                                        break;
                                    case 3 : echo 'San Rafael';
                                        break;
                                    case 4 : echo 'San Marcos Sierras';
                                        break;
                                    case 5 : echo 'Las Grutas';
                                        break;
                                    
                                }
                                
                                ?>
                                
                            </span>
			    <div class="flDer"><img width="100%" src="/img/vde-logotipo.png"></div>
			</div><!--btnReq-->
			<div class="clear"></div>
		</div><!--areaRequerimiento-->
	</div><!--page2-->
		
	

        <div id="page3" class="section pEspecies3 fullAlto" onselectstart="return false">

            <div class="divEspecies ocultar">
                <div class="divTxt ocultar">
                    <h2>Disfrutá</h2>
                    <p>de los paisajes, las playas y de la amplia  diversidad cultural de la argentina:  recitales, musicales de todos los géneros, teatro para grandes y chicos, muestras, conferencias, juegos, libros y entretenimientos.
Elegí tu lugar y viví un verano pleno de emociones.</p>
                    <div class="clear"></div>
                </div><!--divTxt-->
                <div data-clase="c1" data-idajax="1" data-800-top="margin-top:150px;" data-600-top="margin-top:50px;" class="especie btnEspecie btnDespleDer skrollable skrollable-before" style="margin-top: 100px;">
                    <img width="280"  src="/img/mdq.png">
                </div>
                <div data-clase="c2" data-idajax="2" data-800-top="margin-top:150px;" data-600-top="margin-top:50px;" class="especie btnEspecie btnDespleDer skrollable skrollable-before" style="margin-top: 100px;">
                    <img width="280"  src="/img/ezeiza.png">
                </div>
                
                <div class="clear"></div>
                <div data-clase="c3" data-idajax="3" data-800-top="margin-top:100px;" data-600-top="margin-top:-10px;" class="especie btnEspecie btnDespleDer skrollable skrollable-before" style="margin-top: 100px;">
                    <img width="280"  src="/img/sanrafael.png">
                </div>
                <div data-clase="c4" data-idajax="4" data-800-top="margin-top:100px;" data-600-top="margin-top:-10px;" class="especie btnEspecie btnDespleDer skrollable skrollable-before" style="margin-top: 100px;">
                    <img width="280"  src="/img/sanmarcos.png">
                </div>
                <div data-clase="c5" data-idajax="5" data-800-top="margin-top:100px;" data-600-top="margin-top:-10px;" class="especie btnEspecie btnDespleDer skrollable skrollable-before" style="margin-top: 100px;">
                    <img width="280"  src="/img/lasgrutas.png">
                </div>


                <div class="clear"></div>
            </div><!--divEspecies-->
            <div class="areaBotones ocultar skrollable skrollable-before" data-700-top="right:-184px" data-500-top="right:0;" >
			<div class="btns">
                            <a data-idactividad="fiestas" href="#" class="btnActividades"><img width="80%" src="/img/bt_fiestas.png"></a>
                            <a data-idactividad="casas" href="#" class="btnActividades"><img width="80%" src="/img/bt_casas.png"></a>
			</div><!--btnReq-->
			<div class="clear"></div>
		</div><!--areaRequerimiento-->

        </div><!--page6-->
	
	<div id="page8" class="section pDescargas guarda" style="min-height: 800px; background-position: 0px 0px;">
		<div class="txt1 ocultar skrollable skrollable-before" data-600-top="top:150px;" data-300-top="top:75px;" style="top: 150px;">
			<p>mas imágenes</p>
		</div><!--txt1-->
		<div class="titular ocultar skrollable skrollable-before" data-750-top="left:55%;" data-350-top="left:45%;" style="left: 55%;">Galería</div>
		<div class="dataDescargas">
                    
                    
    <div id="owl-galeria" class="owl-carousel">
    </div>

                    
			
                </div><!--dataDescargas-->
	</div><!--page8-->

</div><!--page-->

<div id="rightPage" class="rightPage" style="display: block; -webkit-transform: translateX(800px);">



</div><!--rightPage-->

<div id="area360" class="area360 btnClose360">
    <div class="areaMap">

        <div class="bntClose btnClose360"><img width="100%" src="/assets/btnFrameClose.png"></div>

        <div id="lbMaps" class="embed-container">

        </div><!--embed-container-->
    </div><!--areaMap-->
</div><!--area360-->

<div id="areaLugares" class="areaLugares" onselectstart="return false">

</div><!--areaLugares-->

<!-- Owl Carousel Assets -->
<link href="/css/owl.transitions.css" rel="stylesheet">




</div><!--full-->

