
<div id="full" class="full" ondragstart="return false" style="">
	
	<!--loading-->
	
	<div id="loadingAjax" class="loadingAjax" style="display: none;">
		<div class="clLoading"></div>
	</div><!--loadingAjax-->
	
	<div id="loadingAjaxLug" class="loadingAjaxLug">
		<div class="clLoading"></div>
	</div><!--loadingAjaxLug-->
	
	<!--intro-->
	
	
	

<div class="btnFrameClose ocultarDer" style="display: none;">
	<div class="rf r1"></div>
	<div class="rf r2"></div>
	<div class="rf r3"></div>
</div><!--btnMenu-->

<div class="frameClose ocultarDer" style="display: none;"></div>

<div id="page" class="page smoothWheel">
	
	<div id="btnMenu" class="btnMenu">
		<div class="rf r1"></div>
		<div class="rf r2"></div>
		<div class="rf r3"></div>
	</div><!--btnMenu-->
	
	<div id="menu" class="menu">
		<?php echo $this->partial('menu.phtml') // <-- Add this!! ?>
    
	</div><!--menu-->
        
	<div id="page1" class="section pInicio fullAlto skrollable ">
            <div class="pInicioImg fullAlto ocultar skrollable  " data-0="background-position:0 20px;" data-700="background-position:0 -500px;" >
                  <!-- <img src="/img/tipitos.png"> -->
            </div>
                
		
            <div class="txt1 ocultar skrollable " data-0="margin-top:-50px;" data-500="margin-top:100px;">
                   
			<div id="conteBajar" class="conteBajar">
				<!-- 
    <div class="ic1"><img src="/img/vde-logotipo.png"></div>

                            <div class="ic2"><img src="/img/vde-logob.png"></div>-->
			</div><!--conteBajar-->
		</div><!--txt1-->
                <div class="cucarda ocultar skrollable" data-500="top:1% ; left:0%;" data-600="top:1% ; left:-85%;" >
			<div style="height:68px; padding:9px 4px 0 90px">
				<img width="520" src="/img/logos.png">
			</div><!--btnReq-->
			<div class="clear"></div>
		</div>
          <style>
         .cucarda    {background: none repeat scroll 0 0 rgba(250, 250, 250, 0.8);
    border-bottom-left-radius: 2px;
    border-top-left-radius: 2px;
    display: block;
    position: fixed;
    left:0;
    right: 0;
    width: 630px;
    z-index: 3;}
        </style>
	</div><!--inicio-->
	
	<div id="page2" class="section pCamino fullAlto" style="background: url('/img/p2-bg-<?php  echo $this->imgnrand ?>.jpg') no-repeat scroll center center / cover rgba(0, 0, 0, 0); ">
		<div class="titular ocultar skrollable " data-500-top="top: 80px" data-250-top="top: 45px" >
                    <?php
                                switch($this->imgnrand){
                                    case 1 : echo 'Disfrutá de Mar del Plata';
                                        break;
                                    case 2 : echo 'Divertite en <br>los Piletones de Ezeiza';
                                        break;
                                    case 3 : echo 'Conocé San Rafael';
                                        break;
                                    case 4 : echo 'Relajate en <br>San Marcos Sierras';
                                        break;
                                    case 5 : echo 'Descubrí Las Grutas';
                                        break;
                                    
                                }
                                
                                ?></div>
		<div class="areaInfo ocultar skrollable " data-750-top="width:35%;" data-450-top="width:45%;">
			<div class="caminoInfo">
				

    <div id="owl-demo" class="owl-carousel">
    </div>

<?php  // echo $this->imgnrand ?>
				
			</div><!--caminoInfo-->
			<div class="clear"></div>
		</div><!--areaInfo-->
		<div class="areaRequerimiento ocultar skrollable skrollable-before" data-700-top="width:35%;" data-500-top="width:40%;">
			<div class="btnReq">
                            <span>
                                <?php
                                switch($this->imgnrand){
                                    case 1 : echo 'Mar del Plata';
                                        break;
                                    case 2 : echo 'Ezeiza';
                                        break;
                                    case 3 : echo 'San Rafael';
                                        break;
                                    case 4 : echo 'San Marcos Sierras';
                                        break;
                                    case 5 : echo 'Las Grutas';
                                        break;
                                    
                                }
                                
                                ?>
                                
                            </span>
			    <div class="flDer"><img width="100%" src="/img/vde-logotipo.png"></div>
			</div><!--btnReq-->
			<div class="clear"></div>
		</div><!--areaRequerimiento-->
	</div><!--page2-->
	<?php /* ?>	
	<div id="page3" class="section pIslas fullAlto skrollable skrollable-before" data-top="background-position:0px 0px;" data-top-bottom="background-position:0px 400px;" onselectstart="return false" style="min-height: 800px; background-position: 0px 0px;">
		<div class="islasImg ocultar skrollable skrollable-before" data-700-top="margin-top:-100px;" data-500-top="margin-top:-250px;" style="margin-top: -100px;">
			<img class="islasImgImg" src="/img/mapa.png">
			<div data-idajax="1" class="btnIsla pDer btnDespleDer i1">  <div class="ic"><img class="pin" src="/assets2/pin.png"></div> <div class="clear"></div> </div>
			<div data-idajax="2" class="btnIsla pIz btnDespleDer i2"><div class="ic"><img class="pin" src="/assets2/pin.png"></div> <div class="clear"></div> </div>
			<div data-idajax="3" class="btnIsla pDer btnDespleDer i3"><div class="ic"><img class="pin" src="/assets2/pin.png"></div> <div class="clear"></div> </div>
			<div data-idajax="4" class="btnIsla pIz btnDespleDer i4"><div class="ic"><img class="pin" src="/assets2/pin.png"></div> <div class="clear"></div> </div>
                        <div data-idajax="4" class="btnIsla pIz btnDespleDer i5"><div class="ic"><img class="pin" src="/assets2/pin.png" <img class="gra" src="./Galápagos    Ecuador ama la vida3_files/graMorado.png"></div> <div class="clear"></div> </div>
		</div><!--islasImg
		<div class="txtIslas ocultar">
			<h2>Islas</h2>
			<p>Las Islas Encantadas están formadas por <b>13</b> islas mayores, <b>6</b> islas menores, <b>42</b> islotes y muchas rocas, que cubren en total una superficie de <b>7,850 km².</b></p>
			<div class="clear"></div>
		</div>
        
        txtIslas-->
	</div><!--pIslas--><?php */ ?>
	<?php /* ?>
	<div id="page4" class="section pAveBlanca fullAlto skrollable skrollable-before" data-top="background-position:0px 0px;" data-top-bottom="background-position:0px 400px;" style="min-height: 800px; background-position: 0px 0px;">
		<div class="ave ocultar skrollable skrollable-before" data-300-top="bottom:100px; left:5%;" data-top-bottom="bottom: 400px; left:50%;" style="bottom: 100px; left: 5%;">
			<img src="./Galápagos    Ecuador ama la vida3_files/page2Ave.png">
		</div><!--ave-->
		<div class="txt1 ocultar skrollable skrollable-before" data-300-top="top:150px;" data-top-bottom="top:450px;" style="top: 150px;">
			<p>Galápagos es conocida por sus numerosas especies endémicas y por los estudios de Charles Darwin que le llevaron a establecer su teoría de la evolución.</p>
			<p>Este extraordinario laboratorio natural fue declarado Patrimonio de la Humanidad por la Unesco.</p>
		</div><!--txt1-->
		<div class="comentario ocultar skrollable skrollable-before" data-300-top="bottom:65px;" data-top-bottom="bottom:10px;" style="bottom: 65px;">
			<div class="txt">
				<span class="verde">"Son el destino más famoso del mundo para la observación de la vida salvaje."</span>
				<span class="blanco">Mark Carwardine, zoólogo</span>
			</div><!--txt-->
		</div><!--comentario-->
	</div><!--page4-->
	<?php * ?>
	<div id="page5" class="section pEspecies fullAlto" style="min-height: 800px;">
		<div class="titular ocultar skrollable skrollable-before" data-250-top="top:50px;" data-top-bottom="top:200px;" style="top: 50px;">Especies</div>
		
		<div class="esp1 fullAlto box skrollable " data-10="display:none;" data-1500-bottom="display:block;" data-top="opacity:1;" data--100-top="opacity:0" style="min-height: 800px; display: none; opacity: 1;">
			<div class="tortuga skrollable skrollable-before" data-700-top="bottom:250px; left:5%;" data-top-bottom="bottom: 500px; left:30%;" style="bottom: 250px; left: 5%;">
				<img src="./Galápagos    Ecuador ama la vida3_files/bgEspecieTortuga.png">
			</div><!--tortuga-->
			<div class="areaTxt ocultar skrollable skrollable-before" data-600-top="top:200px;" data-400-top="top:300px;" style="top: 200px;">
				<h2>Reserva marina</h2>
				<div class="bgNegro">
					Los ecosistemas terrestres de las islas no pueden sobrevivir sin una protección paralela del ambiente marino adyacente. Por este motivo el 18 de marzo de 1999 se hizo efectiva la Reserva Marina de Galápagos, cuyos límites son de 40 millas tomadas desde la línea base de las islas exteriores del archipiélago, formando con esto la segunda mayor reserva marina del mundo.				</div><!--bgNegro-->
			</div><!--areaTxt-->
		</div><!--esp1-->
		
		<div class="esp2 fullAlto box" style="min-height: 800px;">
			<div class="areaTxt ocultar skrollable skrollable-before" data-400-top="bottom:200px;" data-top-bottom="bottom:100px;" style="bottom: 200px;">
				<div class="bgNegro">
					<p>Esta área presenta características biológicas extraordinarias, debido principalmente a corrientes oceánicas provenientes de regiones tropicales y subtropicales que convergen en las islas, trayendo animales de todo el Pacífico y parte del Indo-Pacífico, creando una gran biodiversidad y produciendo a la vez una cortina de aislamiento genético. Las temperaturas de estas corrientes también contribuyen con la variedad de ecosistemas marinos.</p>
					<p>Es por esto que aquí hay un 23% de endemismo y también es el único refugio para especies amenazadas de reptiles y mamíferos marinos, como tortugas y ballenas, que encuentran en el archipiélago su principal sitio de reproducción.</p>
				</div><!--bgNegro-->
				<div class="clear"></div>
			</div><!--areaTxt-->
		</div><!--esp2-->
	</div><!--pEspecies-->
	
        <div id="page3" class="section pIslas fullAlto skrollable skrollable-before" data-top="background-position:0px 0px;" data-top-bottom="background-position:0px 400px;" onselectstart="return false">
            
            <div class="islasImg ocultar skrollable skrollable-before " data-500-top="margin-top:-20px;" data-200-top="margin-top:-370px;">
			
			<div data-idajax="1" class="btnIsla pDer btnDespleDer i1">  <div class="ic"><img width="240" src="/img/sanmarcos.png"></div> <div class="clear"></div> </div>
			<div data-idajax="2" class="btnIsla pIz btnDespleDer i2"><div class="ic"><img width="240"  src="/img/ezeiza.png"></div> <div class="clear"></div> </div>
			<div data-idajax="3" class="btnIsla pDer btnDespleDer i3"><div class="ic"><img width="240"  src="/img/sanrafael.png"></div> <div class="clear"></div> </div>
			<div data-idajax="4" class="btnIsla pIz btnDespleDer i4"><div class="ic"><img width="240"  src="/img/mdq.png"></div> <div class="clear"></div> </div>
                        <div data-idajax="4" class="btnIsla pIz btnDespleDer i5"><div class="ic"><img width="240"  src="/img/lasgrutas.png"></div> <div class="clear"></div> </div>
                        
                        
                        
                        
		</div><!--islasImg
		<div class="txtIslas ocultar">
			<h2>Islas</h2>
			<p>Las Islas Encantadas están formadas por <b>13</b> islas mayores, <b>6</b> islas menores, <b>42</b> islotes y muchas rocas, que cubren en total una superficie de <b>7,850 km².</b></p>
			<div class="clear"></div>
		</div>
        
        txtIslas-->
	</div>
          <?php */ ?>

        <div id="page6" class="section pEspecies3 fullAlto" onselectstart="return false">

            <div class="divEspecies ocultar">
                <div class="divTxt ocultar">
                    <h2>Disfrutá</h2>
                    <p>de paisajes, playas, comidas, excursiones, turismo, museos y tus propias aventuras, elegí tu lugar y viví verano de emociones </p>
                    <div class="clear"></div>
                </div><!--divTxt-->
                <div data-clase="c1" data-idajax="1" data-800-top="margin-top:150px;" data-600-top="margin-top:50px;" class="especie btnEspecie btnDespleDer skrollable skrollable-before" style="margin-top: 100px;">
                    <img width="280"  src="/img/mdq.png">
                </div>
                <div data-clase="c2" data-idajax="2" data-800-top="margin-top:150px;" data-600-top="margin-top:50px;" class="especie btnEspecie btnDespleDer skrollable skrollable-before" style="margin-top: 100px;">
                    <img width="280"  src="/img/ezeiza.png">
                </div>
                
                <div class="clear"></div>
                <div data-clase="c3" data-idajax="3" data-800-top="margin-top:100px;" data-600-top="margin-top:-10px;" class="especie btnEspecie btnDespleDer skrollable skrollable-before" style="margin-top: 100px;">
                    <img width="280"  src="/img/sanrafael.png">
                </div>
                <div data-clase="c4" data-idajax="4" data-800-top="margin-top:100px;" data-600-top="margin-top:-10px;" class="especie btnEspecie btnDespleDer skrollable skrollable-before" style="margin-top: 100px;">
                    <img width="280"  src="/img/sanmarcos.png">
                </div>
                <div data-clase="c5" data-idajax="5" data-800-top="margin-top:100px;" data-600-top="margin-top:-10px;" class="especie btnEspecie btnDespleDer skrollable skrollable-before" style="margin-top: 100px;">
                    <img width="280"  src="/img/lasgrutas.png">
                </div>


                <div class="clear"></div>
            </div><!--divEspecies-->
            <div class="areaBotones ocultar skrollable skrollable-before" data-700-top="right:-184px" data-500-top="right:0;" >
			<div class="btns">
                            <a data-idactividad="fiestas" href="#" class="btnActividades"><img width="80%" src="/img/bt_fiestas.png"></a>
                            <a data-idactividad="casas" href="#" class="btnActividades"><img width="80%" src="/img/bt_casas.png"></a>
			</div><!--btnReq-->
			<div class="clear"></div>
		</div><!--areaRequerimiento-->

        </div><!--page6-->
	<?php /* ?>	
	<div id="page7" class="section pEvolucion fullAlto skrollable skrollable-before" data-750-top="background-position:0px -200px;" data-100-top="background-position:0px 0px;" style="min-height: 800px; background-position: 0px -200px;">
		<div class="titular ocultar skrollable skrollable-before" data-750-top="margin-right:-550px;" data-500-top="margin-right:-450px;" style="margin-right: -550px;">Evolución &amp; relax</div>
		<div class="dataEvolution ocultar">
			
			<div class="item iz skrollable skrollable-before" data-850-top="margin-top:100px;" data-600-top="margin-top:0px;" style="margin-top: 100px;">
				<div class="icon"> <img width="100%" src="./Galápagos    Ecuador ama la vida3_files/ico1.png"> </div>
				<h3>Turismo de naturaleza y cultural</h3>
				<div class="sepBar"></div>
				<p>Las Islas Encantadas son también la cuna de la Teoría del Origen de las Especies de Charles Darwin, quien las visitó en 1835. En la actualidad las islas contienen uno de los grupos volcánicos más activos del mundo.</p>
			</div><!--item-->
			
			<div class="item cen skrollable skrollable-before" data-800-top="margin-top:200px;" data-600-top="margin-top:0px;" style="margin-top: 200px;">
				<div class="icon"> <img width="100%" src="./Galápagos    Ecuador ama la vida3_files/ico2.png"> </div>
				<h3>Turismo de aventura</h3>
				<div class="sepBar"></div>
				<p>En Galápagos se puede hace kayak, surfear, bucear en las profundidades, hacer cicloturismo y practicar snorkel superficialmente. Y todas estas emocionantes actividades dentro de un entorno seguro y paisajes únicos.</p>
			</div><!--item-->
			
			<div class="item der skrollable skrollable-before" data-750-top="margin-top:300px;" data-600-top="margin-top:0px;" style="margin-top: 300px;">
				<div class="icon"> <img width="100%" src="./Galápagos    Ecuador ama la vida3_files/ico3.png"> </div>
				<h3>Cruceros</h3>
				<div class="sepBar"></div>
				<p>La mejor forma de disfrutar y conocer las Islas Encantadas es hospedarse en cruceros y viajar por barco a cada isla, así puedes conocer incluso las más alejadas. Un guía naturalista siempre viaja en los cruceros.</p>
			</div><!--item-->
			
			<!--div class="clear"></div-->
		</div><!--dataEvolution-->
	</div><!--page7-->
<?php */ ?>
	<div id="page8" class="section pDescargas guarda" style="min-height: 800px; background-position: 0px 0px;">
		<div class="txt1 ocultar skrollable skrollable-before" data-600-top="top:150px;" data-300-top="top:75px;" style="top: 150px;">
			<p>mas imágenes</p>
		</div><!--txt1-->
		<div class="titular ocultar skrollable skrollable-before" data-750-top="left:55%;" data-350-top="left:45%;" style="left: 55%;">Galería</div>
		<div class="dataDescargas">
			<div class="wallpapers">
				<div class="imagen">
					<img src="/assets/Galapagos-1M.jpg">
					<div class="resoluciones">
						<a class="" download="Flamingos.jpg" href="http://visit.ecuador.travel/galapagos/img/descargas/Galapagos-1-1920x1080.jpg" target="_blank"><span>Horizontal</span></a>
						<a class="der" download="Flamingos.jpg" href="http://visit.ecuador.travel/galapagos/img/descargas/Galapagos-1-1080x1920.jpg" target="_blank"><span>Vertical</span></a>
						<div class="clear"></div>
					</div>
				</div><!--imagen-->
				
				<div class="imagen">
					<img src="/assets/Galapagos-2M.jpg">
					<div class="resoluciones">
						<a class="" download="Iguanas Marinas.jpg" href="http://visit.ecuador.travel/galapagos/img/descargas/Galapagos-2-1920x1080.jpg" target="_blank"><span>Horizontal</span></a>
						<a class="der" download="Iguanas Marinas.jpg" href="http://visit.ecuador.travel/galapagos/img/descargas/Galapagos-2-1080x1920.jpg" target="_blank"><span>Vertical</span></a>
						<div class="clear"></div>
					</div>
				</div><!--imagen-->
				
				<div class="imagen">
					<img src="/assets/Galapagos-3M.jpg">
					<div class="resoluciones">
						<a class="" download="Pinguinos.jpg" href="http://visit.ecuador.travel/galapagos/img/descargas/Galapagos-3-1920x1080.jpg" target="_blank"><span>Horizontal</span></a>
						<a class="der" download="Pinguinos.jpg" href="http://visit.ecuador.travel/galapagos/img/descargas/Galapagos-3-1080x1920.jpg" target="_blank"><span>Vertical</span></a>
						<div class="clear"></div>
					</div>
				</div><!--imagen-->
				
				<div class="imagen">
					<img src="/assets/Galapagos-4M.jpg">
					<div class="resoluciones">
						<a class="" download="Piquero de patas azules.jpg" href="http://visit.ecuador.travel/galapagos/img/descargas/Galapagos-4-1920x1080.jpg" target="_blank"><span>Horizontal</span></a>
						<a class="der" download="Piquero de patas azules.jpg" href="http://visit.ecuador.travel/galapagos/img/descargas/Galapagos-4-1080x1920.jpg" target="_blank"><span>Vertical</span></a>
						<div class="clear"></div>
					</div>
				</div><!--imagen-->
				
				<div class="imagen">
					<img src="/assets/Galapagos-5M.jpg">
					<div class="resoluciones">
						<a class="" download="Tortugas de Galápagos.jpg" href="http://visit.ecuador.travel/galapagos/img/descargas/Galapagos-5-1920x1080.jpg" target="_blank"><span>Horizontal</span></a>
						<a class="der" download="Tortugas de Galápagos.jpg" href="http://visit.ecuador.travel/galapagos/img/descargas/Galapagos-5-1080x1920.jpg" target="_blank"><span>Vertical</span></a>
						<div class="clear"></div>
					</div>
				</div><!--imagen-->
				
				<div class="imagen">
					<img src="/assets/Galapagos-6M.jpg">
					<div class="resoluciones">
						<a class="" download="Fragatas.jpg" href="http://visit.ecuador.travel/galapagos/img/descargas/Galapagos-6-1920x1080.jpg" target="_blank"><span>Horizontal</span></a>
						<a class="der" download="Fragatas.jpg" href="http://visit.ecuador.travel/galapagos/img/descargas/Galapagos-6-1080x1920.jpg" target="_blank"><span>Vertical</span></a>
						<div class="clear"></div>
					</div>
				</div><!--imagen-->
				
				<div class="imagen">
					<img src="/assets/Galapagos-7M.jpg">
					<div class="resoluciones">
						<a class="" download="Lobos Marinos.jpg" href="http://visit.ecuador.travel/galapagos/img/descargas/Galapagos-7-1920x1080.jpg" target="_blank"><span>Horizontal</span></a>
						<a class="der" download="Lobos Marinos.jpg" href="http://visit.ecuador.travel/galapagos/img/descargas/Galapagos-7-1080x1920.jpg" target="_blank"><span>Vertical</span></a>
						<div class="clear"></div>
					</div>
				</div><!--imagen-->
				
				<div class="clear"></div>
			</div><!--wallpapers-->
                </div><!--dataDescargas-->
	</div><!--page8-->

</div><!--page-->

<div id="rightPage" class="rightPage" style="display: block; -webkit-transform: translateX(800px);">



</div><!--rightPage-->

<div id="area360" class="area360 btnClose360">
    <div class="areaMap">

        <div class="bntClose btnClose360"><img width="100%" src="/assets/btnFrameClose.png"></div>

        <div id="lbMaps" class="embed-container">

        </div><!--embed-container-->
    </div><!--areaMap-->
</div><!--area360-->

<div id="areaLugares" class="areaLugares" onselectstart="return false">

</div><!--areaLugares-->

<!-- Owl Carousel Assets -->
<link href="/css/owl.transitions.css" rel="stylesheet">




</div><!--full-->

