
<div id="full" class="full" ondragstart="return false" style="">

    <!--loading-->

    <div id="loadingAjax" class="loadingAjax" style="display: none;">
        <div class="clLoading"></div>
    </div><!--loadingAjax-->

    <div id="loadingAjaxLug" class="loadingAjaxLug">
        <div class="clLoading"></div>
    </div><!--loadingAjaxLug-->

    <!--intro-->




    <div class="btnFrameClose ocultarDer" style="display: none;">
        <div class="rf r1"></div>
        <div class="rf r2"></div>
        <div class="rf r3"></div>
    </div><!--btnMenu-->

    <div class="frameClose ocultarDer" style="display: none;"></div>

    <div id="page" class="page smoothWheel">

        <div id="btnMenu" class="btnMenu">
            <div class="rf r1"></div>
            <div class="rf r2"></div>
            <div class="rf r3"></div>
        </div><!--btnMenu-->

        <div id="menu" class="menu">
            <?php echo $this->partial('menu.phtml') // <-- Add this!! ?>

        </div><!--menu-->

        <div id="page1" class="section pInicio fullAlto ">
            <div class="pInicioImg fullAlto ocultar skrollable  "  >

               <!-- <img src="/img/tipitos.png"> -->
            </div>


            <div class="txt1 ocultar skrollable " data-0="margin-top:-50px;" data-500="margin-top:100px;">

                <div id="conteBajar" class="conteBajar">


                    <div class="ic2"><img width="180" src="/img/scroll.png"></div>
                </div><!--conteBajar-->
            </div><!--txt1-->
            <div class="cucarda ocultar skrollable" data-500="top:1% ; left:0%;" data-600="top:1% ; left:-85%;" >
                <div style="height:68px; padding:9px 4px 0 90px">
                    <img width="520" src="/img/logos.png">

                </div><!--btnReq-->
                <div class="clear"></div>
            </div>
            </div><!--inicio-->

            <div id="page2" class="section pCamino fullAlto" style="background: url('/img/p2-bg-<?php echo $this->imgnrand ?>.jpg') no-repeat scroll center center / cover rgba(0, 0, 0, 0); ">
            <div class="titular ocultar skrollable " data-500-top="top: 80px" data-250-top="top: 45px" >
                <?php
                switch ($this->imgnrand) {
                    case 1 : echo 'Disfrutá de Mar del Plata';
                        break;
                    case 2 : echo 'Divertite en <br>los Bosques de Ezeiza';
                        break;
                    case 3 : echo 'Conocé San Rafael';
                        break;
                    case 4 : echo 'Relajate en <br>San Marcos Sierras';
                        break;
                    case 5 : echo 'Descubrí Las Grutas';
                        break;
                }
                ?></div>
            <div class="areaInfo ocultar skrollable " data-750-top="width:45%;" data-450-top="width:55%;">
                <div class="caminoInfo">
                    
                    <div id="owl-noticias" class="owl-carousel">
                        
                        <?php if($this->noticias){
                            $this->partialloop()->setObjectKey('noticia');
                        echo $this->partialloop('owlNoticia', $this->noticias); } else { ?>

                        
                        <div class="item">
                            <div class="noticap"><h1>MAR DEL PLATA SE SUMA AL "VERANO DE EMOCIONES"</h1><p>
El miércoles 14 de enero Mar del Plata se suma a Verano de Emociones cuando la Base Naval abra sus puertas para que puedas visitar el parque Paleontológico y sus dinosaurios, la Fragata Libertad, puedas sumarte a las partidas de ajedrez con Ajedrecear, hacer tus instrumentos con  Hacelo Sonar,  disfrutar el Tango de mil amores, recorrer la feria de comidas y artesanías, la kermes de Paka Paka y mucho más. El cierre será a pleno con la presentación de URRAKA y todo el ritmo de LA MOSCA.
                                </p></div>                                                                                                           
                            <img src="https://farm8.staticflickr.com/7533/16059090730_7afbbe054b_q.jpg" width="190" height="190" alt="Urraka en San Rafael 3">
                        </div>
                        <div class="item">
                            <div class="noticap"><h1>SORPRENDENTE MUESTRA SOBRE EL  CUERPO HUMANO</h1><p>
 De la mano de Verano de Emociones, el Ministerio de Ciencia y Tecnología acerca a San Rafael la muestra Cuerpo Humano: Ciencia por Dentro, en la que podrás conocer nuestro organismo y entender nuestra fisonomía, como la forma en la que los músculos se relacionan con los huesos para permitir movernos, la importancia de la piel como aislante del entorno y el esqueleto como sostén.  La muestra del Ministerio de Ciencia y Tecnología cuenta con la guía de estudiantes de medicina de la Universidad Nacional de La Matanza que nos acompañarán en esta maravillosa experiencia educativa.
                                </p></div>
                            <img src="https://farm8.staticflickr.com/7562/16280392061_06c36d542a_q.jpg" width="190" height="190" alt="Urraka en San Rafael 3">
                        </div>
                        <div class="item">
                            <div class="noticap"><h1>UN VERANO DISTINTO EN LAS GRUTAS</h1><p>
        El “Verano de emociones” llegó a Las Grutas el 11 de enero con un día a pleno sol.

A pura reposera y mate, la plaza de la Avenida Boulevard recibió a vecinos y turistas que desafiaron a maestros del ajedrez, escucharon los consejos sobre salud, visitaron el aula rodante y  las ferias, y se instalaron al caer la tarde frente al escenario principal, para ver el musical para chicos de “Hora Libre” y escuchar a los locales Intokables y D5. El gran cierre estuvo a cargo de Iván Noble que hizo bailar y cantar a Las Grutas con sus éxitos.
                                </p></div>
                            <img src="https://farm8.staticflickr.com/7526/16282224085_14f1cbc05f_q.jpg" width="190" height="190" alt="Urraka en San Rafael 3">
                        </div>
                        <div class="item">
                            <div class="noticap"><h1>San Marcos Sierras se suma a Verano de Emociones</h1><p>
                          A pesar de la lluvia, Verano de Emociones comenzó el 10 de enero con todo en San Marcos Sierras, Córdoba. La muestra de Máscaras y vestimentas de los Pueblos Originarios, Ajedrecear y la feria de artesanos, entre otras actividades, acompañaron el comienzo de Verano en Córdoba, que cerró con los shows de Cuerda Candombe y la fuerza de La Bomba de Tiempo. 
                                </p></div>
                            <img src="https://farm9.staticflickr.com/8606/16256056076_dc19c2bbcd_q.jpg" width="190" height="190" alt="Urraka en San Rafael 3">
                        </div>
                        <div class="item">
                            <div class="noticap"><h1>El Verano arrancó en San Rafael con Miss Boliva</h1><p>
                             El Verano arrancó en San Rafael con Miss Boliva

San Rafael, Mendoza, vivió a pleno el 10 de enero su primer día de Verano de Emociones, con un cierre bien arriba de la mano del ritmo pegadizo de Miss Bolivia.  El Programa organizado por Presidencia de la Nación reúne, hasta el 23 de febrero en el Parque Hipólito Irigoyen, actividades para toda la familia con recitales, juegos, ferias, muestras de ciencia, comidas típicas y mucha cultura. 
                                </p></div>
                            <img src="https://farm9.staticflickr.com/8639/15661777113_f4dced3393_q.jpg" width="190" height="190" alt="Urraka en San Rafael 3">
                        </div>
                        
                        
                        
                        
                        
                        <div class="item">
                            <div class="noticap"><h1>URRAKA HIZO BAILAR A SAN RAFAEL, MENDOZA.</h1><p>Nunca pensaste que con instrumentos cotidianos podrías hacer música? Urraka lo hace y muy bien! Ayer lo demostró en San Rafael, en la temporada Verano de Emociones, organizado por Presidencia de la Nación. También se presentó Tricoma Fajina, con música que cantaron todos.
<br>Hasta el 23 de febrero hay actividades en San Rafael y en distintos puntos del país.</p></div>
                            <img src="https://farm9.staticflickr.com/8679/15644492683_602f58fa57_q.jpg" width="190" height="190" alt="Urraka en San Rafael 3">
                        </div>
                        <div class="item">
                            <div class="noticap"><h1>
                                    UN VERANO DISTINTO EN LAS GRUTAS</h1><p>El “Verano de emociones” llegó a Las Grutas en un día radiante con una variada oferta de actividades culturales, artísticas, científicas y recreativas organizadas por Presidencia de la Nación, a través del Ministerio de Cultura y con la participación de otros ministerios.</p></div>
                            <img src="https://farm8.staticflickr.com/7497/16080975899_490481978d_q.jpg" width="190" height="190" alt="Ivan Noble en las Grutas">
                        </div>
                        <div class="item">
                            <div class="noticap"><h1>
                                    NOCHE DE APERTURA EN SAN RAFAEL</h1><p>Así vivió San Rafael, Mendoza, su primer día de Verano de Emociones, organizado por Presidencia de la Nación. Mucha cultura, ciencia, juegos y, un cierre bien arriba de Miss Bolivia!. </p></div>
                            <img src="https://farm8.staticflickr.com/7552/16256467791_649945fccd_q.jpg" width="190" height="190" alt="Apertura San Rafael">
                        </div> <?php }  ?>
                    </div> 
<?php // echo $this->imgnrand  ?>

                </div><!--caminoInfo-->
                <div class="clear"></div>
            </div><!--areaInfo-->


            <div class="areaRequerimiento ocultar skrollable skrollable-before" data-700-top="width:35%;" data-500-top="width:40%;">
                <div class="btnReq"><div class="social">
                        <a target="_blank" href="https://www.facebook.com/pages/Verano-de-Emociones/1605302536365064">Facebook</a><br />
                        <a target="_blank" href="https://twitter.com/VeranoEmociones">Twitter</a><br />
                        <a target="_blank" href="https://www.flickr.com/photos/129741112@N06/sets/">Flickr</a><br />
                        <a target="_blank" href="https://www.youtube.com/channel/UCZSLhlA9XAbJMUQ_yZaO5Mw">YouTube</a>
                    </div>
                    <span>
<?php /*
  switch($this->imgnrand){
  case 1 : echo 'Mar del Plata';
  break;
  case 2 : echo 'Ezeiza';
  break;
  case 3 : echo 'San Rafael';
  break;
  case 4 : echo 'San Marcos Sierras';
  break;
  case 5 : echo 'Las Grutas';
  break;
  }
 */
?>

                    </span>
                    <div class="flDer"><img width="100%" src="/img/vde-logotipo.png"></div>
                </div><!--btnReq-->
                <div class="clear"></div>
            </div><!--areaRequerimiento-->
        </div><!--page2-->



        <div id="page3" class="section pEspecies3 fullAlto" onselectstart="return false">

            <div class="divEspecies ocultar">
                <div class="divTxt ocultar">
                    <h2>Disfrutá</h2>
                    <p>de los paisajes, las playas y de la amplia  diversidad cultural de la Argentina:  recitales, musicales de todos los géneros, teatro para grandes y chicos, muestras, conferencias, juegos, libros y entretenimientos.
                        Elegí tu lugar y viví un verano pleno de emociones.</p>
                    <div class="clear"></div>
                </div><!--divTxt-->
                <div data-clase="c1" data-idajax="1" data-800-top="margin-top:150px;" data-600-top="margin-top:50px;" class="especie btnEspecie btnDespleDer skrollable skrollable-before" style="margin-top: 100px;">
                    <img width="280"  src="/img/mdq.png">
                </div>
                <div data-clase="c2" data-idajax="2" data-800-top="margin-top:150px;" data-600-top="margin-top:50px;" class="especie btnEspecie btnDespleDer skrollable skrollable-before" style="margin-top: 100px;">
                    <img width="280"  src="/img/ezeiza.png">
                </div>

                <div class="clear"></div>
                <div data-clase="c3" data-idajax="3" data-800-top="margin-top:100px;" data-600-top="margin-top:-10px;" class="especie btnEspecie btnDespleDer skrollable skrollable-before" style="margin-top: 100px;">
                    <img width="280"  src="/img/sanrafael.png">
                </div>
                <div data-clase="c4" data-idajax="4" data-800-top="margin-top:100px;" data-600-top="margin-top:-10px;" class="especie btnEspecie btnDespleDer skrollable skrollable-before" style="margin-top: 100px;">
                    <img width="280"  src="/img/sanmarcos.png">
                </div>
                <div data-clase="c5" data-idajax="5" data-800-top="margin-top:100px;" data-600-top="margin-top:-10px;" class="especie btnEspecie btnDespleDer skrollable skrollable-before" style="margin-top: 100px;">
                    <img width="280"  src="/img/lasgrutas.png">
                </div>


                <div class="clear"></div>
            </div><!--divEspecies-->
            <div class="areaBotones ocultar skrollable skrollable-before" data-700-top="right:-184px" data-500-top="right:0;" >
                <div class="btns">
                    <a data-idactividad="fiestas" href="#" class="btnRedondo"><img width="80%" src="/img/bt_fiestas.png"></a>
                    <a data-idactividad="casas" href="#" class="btnRedondo"><img width="80%" src="/img/bt_casas.png"></a>
                </div><!--btnReq-->
                <div class="clear"></div>
            </div><!--areaRequerimiento-->

        </div><!--page6   https://www.flickr.com/photos/129741112@N06/sets/ -->

        <div id="page4" class="section pGaleria fullAlto" style="min-height: 1200px; background-position: 0px 0px;">
            <div class="txt1 ocultar skrollable skrollable-before" data-600-top="top:150px;" data-300-top="top:75px;">
                <a href="https://www.flickr.com/photos/129741112@N06/sets/" target="_blank" title="Verano de Emociones en Flickr">
                    Visitá nuestro Flickr
                </a>
                
            </div><!--txt1-->
            <div class="titular ocultar skrollable skrollable-before" data-750-top="left:62%;" data-350-top="left:49%;">
                <img width="27%" src="/img/foto_galeria.png"><span style="float:right;margin-top:24px">Galería</span>
            </div>
            <div class="dataGaleria">
                
                <div id="owl-destacadas" class="owl-carousel"></div>
                <div id="owl-recitales" class="owl-carousel"></div>
                <div id="owl-grafica" class="owl-carousel"></div>
                
            </div><!--dataDescargas-->
        </div><!--page8-->
        <div id="page9" class="section pSocial " data-750-top="background-position:0px 400px;" data-100-top="background-position:0px 0px;">
	</div>
    </div><!--page-->

    <div id="rightPage" class="rightPage" style="display: block; -webkit-transform: translateX(800px);">



    </div><!--rightPage-->



    <div id="areaLugares" class="areaLugares" onselectstart="return false">

    </div><!--areaLugares-->

    <!-- Owl Carousel Assets -->
    <link href="/css/owl.transitions.css" rel="stylesheet">




</div><!--full-->
<script>
    $('.btnRedondo').click(function (event) {
        event.preventDefault();
        $('#loadingAjaxLug').fadeToggle(250);
        idActividad = $(this).data('idactividad');

        var postDataLug = 'idactividad=' + idActividad;

        $.ajax({
            type: 'POST',
            dataType: 'html',
            cache: true,
            url: '/ajax/actividades',
            data: postDataLug,
            success: function (htmlLug) {

                $('#areaLugares').html(htmlLug).hide().waitForImages(function () {
                    $('#areaLugares').show();
                    $('#loadingAjaxLug').fadeToggle(250);
                    $('body').addClass("sinScroll");
                    //BG Img
                    /*$(".bgLug").interactive_bg({
                     strength: 25,
                     scale: 1.05,
                     animationSpeed: "100ms"
                     });*/
                    $(window).resize(function () {
                        $(".bgLug > .ibg-bg").css({
                            width: $(window).outerWidth(),
                            height: $(window).outerHeight()
                        });
                    });
                    $("#bgLug,#nombreLug,#descripcionLug").css('cursor', 'url(img/cursor.png),auto');

                    $('#closeLug').click(function () {
                        $('body').removeClass("sinScroll");
                        $('#areaLugares').fadeOut(250, function () {
                            $('#areaLugares').html('');
                        });
                        return false;
                    });
                    $('.btnFullImg').not('#closeLug').click(function () {
                        $('.fullImgOcultar').fadeToggle();
                    });
                    //BG Img

                });

            } //success
        }); //ajax

    });
</script>